### ISSUE TITLE
Request for Github & Linkedin icons

### ISSUE THREAD

**Issue by akmur** [WordPress/dashicons#101]
It would be super to have Github & Linkedin too!

**Comment by ruha** [comment]
I second this request.

**Comment by melchoyce** [comment]
Hi there, have you considered using http://fontawesome.io/icons/? We're not currently planning on adding more social icons to Dashicons.

**Comment by safranck** [comment]
Why do you have Google Plus icon but not Linked in? Silly. Now I have to install font awesome or Fontello and use that instead.
