### ISSUE TITLE
vk.com

### ISSUE THREAD

**Issue by gizmus** [WordPress/dashicons#102]
pls something like this
![zv6qpw7ayag](https://cloud.githubusercontent.com/assets/17768907/13678419/88ecd51e-e6ff-11e5-865f-b1c530ba0d60.jpg)
and like this
![ok_logo](https://cloud.githubusercontent.com/assets/17768907/13678460/dfbdf026-e6ff-11e5-83aa-5aa065fe3fa6.png)

**Comment by gennadijbgl** [comment]
yeh, the most popular social networks are necessary, add please

**Comment by melchoyce** [comment]
Hi there, have you considered using http://fontawesome.io/icons/? We're not currently planning on adding more social icons to Dashicons.
