### ISSUE TITLE
Request for Question Mark Icon

### ISSUE THREAD

**Issue by alpha1** [WordPress/dashicons#104]
This would be useful for Help sections, inline documentation and FAQs.

**Comment by nathanduckett** [comment]
@alpha1,

Look a little harder and you will find there is already a help icon _dashicons-editor-help_

Also you may find the _dashicons-info_ useful

**Comment by TheTracyL** [comment]
We are very sorry, but we are not adding new icons unrelated to core functionality at this time.

Thank you,
-Tracy
