### ISSUE TITLE
Improvement: Add title="dashicons-*" to reference each dashicon class on resources page. 

### ISSUE THREAD

**Issue by nathanduckett** [WordPress/dashicons#105]
https://developer.wordpress.org/resource/dashicons/

I use the resources page quite regularly to grab the class of a dashicon but it can be quite annoying sometimes when testing different icons in my theme, having to click on the icon then been forced to the top and then having to re-scroll back down to get another.

Could we implement the class into the title attribute to simply hover over the icon to see the class.

Eg

`<div alt="f328" class="dashicons dashicons-smiley" title="dashicons-smiley">smiley smile</div>`

**Comment by melchoyce** [comment]
Hi there, can you add this as a new ticket to meta trac? https://meta.trac.wordpress.org/newticket All of the development for developer.wordpress.org happens there.
