### ISSUE TITLE
[Feature Request] Add new yes-alt glyph for notification

### ISSUE THREAD

**Issue by shivapoudel** [WordPress/dashicons#108]
IMO this will be a great opinion to display settings enabled and disabled status using below glyph along with [dashicons-dismiss](https://developer.wordpress.org/resource/dashicons/#dismiss) for some settings notification. Thus, there should be `dashicons-yes-alt` with below glyph which is missing currently :)

![yes-alt](https://cloud.githubusercontent.com/assets/3774827/14099658/2091007e-f5a7-11e5-84da-232be557885f.png)

CC @melchoyce

**Comment by TheTracyL** [comment]
Thank you, @shivapoudel for this suggestion.

This is now added to Trac ticket: https://core.trac.wordpress.org/ticket/41074

**Comment by field2** [comment]
Fixed with https://github.com/WordPress/dashicons/commit/cc333651e31b9cd08bd2af932070a3859c2c4cfc
