### ISSUE TITLE
ORCID

### ISSUE THREAD

**Issue by steko** [WordPress/dashicons#109]
Hello,
it would be great if the @ORCID icon could be added to dashicons. Detailed information and images in various resolutions are available from this page https://orcid.org/trademark-and-id-display-guidelines?lang=en 

> [ORCID](http://orcid.org/) provides a persistent digital identifier that distinguishes you from every other researcher and, through integration in key research workflows such as manuscript and grant submission, supports automated linkages between you and your professional activities ensuring that your work is recognized.

E.g. my ORCID is: 

![Stefano Costa](http://orcid.org/sites/default/files/images/orcid_16x16%281%29.gif)  orcid.org/0000-0003-1124-3174 

And it would be nice to add it to WordPress in the same way as my GitHub and Twitter accounts.

**Comment by mac2net** [comment]
yes please do this!

**Comment by TheTracyL** [comment]
We are very sorry, but we are not adding new icons unrelated to core functionality at this time.

Thank you,
-Tracy
