### ISSUE TITLE
Add an editor-rtl for RTL languages

### ISSUE THREAD

**Issue by fduraibi** [WordPress/dashicons#111]
I would like to have the RTL version of https://developer.wordpress.org/resource/dashicons/#editor-rtl.

I use both icons (LTR & RTL) in my plugin [WP-RTL](https://wordpress.org/plugins/wp-rtl/) and I had to override the dashicon with the old tinymce icons since dashicon only carries the LTR version.

Note: the dashicon `dashicons-editor-rtl` is actually LTR but incorrectly named as RTL! that need to be fixed also.

**Comment by Erezbiox1** [comment]
+

**Comment by TheTracyL** [comment]
Hello @fduraibi,

Thank you or making this suggestion. It is a very good idea and we are going to add it to a ticket for the 4.9 release cycle.

-Tracy

**Comment by TheTracyL** [comment]
This is now added to Trac ticket: https://core.trac.wordpress.org/ticket/41074

**Comment by field2** [comment]
Fixed with https://github.com/WordPress/dashicons/commit/cc333651e31b9cd08bd2af932070a3859c2c4cfc
