### ISSUE TITLE
Version numbers for dashicons in the index

### ISSUE THREAD

**Issue by danieliser** [WordPress/dashicons#116]
It had never occurred to me that all of these wonderful dashicons were not all backward compatible. IE the menu (hamburger) icon was there in 4.1, but the warning sign wasn't.

I think adding the version each was added to the dashicons site would be useful info. Not sure if this is the right place or not.

**Comment by TheTracyL** [comment]
Hello,

It would be a difficult task to go back and map the icons to WP version numbers, therefore we have no plans to do that.

Sorry about that!
-Tracy
