### ISSUE TITLE
Dashicons plus icon appears off-center

### ISSUE THREAD

**Issue by ocean90** [WordPress/dashicons#118]
Original report: https://core.trac.wordpress.org/ticket/31506

> The WordPress Dashicon "plus" appears to be off-center in comparison to the other dashicons. For example, on the [Dashicons page](https://developer.wordpress.org/resource/dashicons/), we can see the icons is not quite vertically aligned with the other Notifications icons.
> 
> ![image](https://cloud.githubusercontent.com/assets/617637/15270053/d6d6ca00-1a12-11e6-8b79-1d448c0d11cc.png)
> 
> The horizontal centering is also off, as can be seen in this image I assembled.
> 
> ![image](https://cloud.githubusercontent.com/assets/617637/15270054/de026c80-1a12-11e6-98f3-5a5023d63ed2.png)
> 
> You can also see the difference on the GitHub repository, between [plus](https://github.com/melchoyce/dashicons/blob/master/svg/plus.svg) and [plus-alt](https://github.com/melchoyce/dashicons/blob/master/svg/plus-alt.svg). This makes the icon quite difficult to use.

**Comment by field2** [comment]
It will make the plus skinnier. We can get away with a 3px wide plus symbol not aligning with the grid by nudging it up and over, but I'm not sure that will work with the circle plus. I can commit a version to test if you think it's worth it.
