### ISSUE TITLE
@font-face font format not recognized

### ISSUE THREAD

**Issue by Jevuska** [WordPress/dashicons#119]
I encountered the following errors in **Microsoft Edge console** when enter admin dashboard:
CSS3113:@font-face font format not recognized
dashicons.eot
CSS3120: No fonts available for @font-face rule
load-styles.php (0,37)

This is the following explanation of error code https://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&l=EN-US&k=k%28VS.WebClient.Help.CSS3113%29#cssCodes

**Comment by melchoyce** [comment]
Hi there, can you add a new Trac ticket for this issue? https://core.trac.wordpress.org/newticket
