### ISSUE TITLE
Squirrel icon

### ISSUE THREAD

**Issue by johnhodge** [WordPress/dashicons#123]
Hey there,

Can we add this squirrel to the dashicons font?
(https://cloud.githubusercontent.com/assets/18251637/16346408/2b28faf2-3a15-11e6-88d8-a922113cc52b.png)

**Comment by melchoyce** [comment]
This is very specific. Why a squirrel?

Related: #59

**Comment by TheTracyL** [comment]
We are very sorry, but we are not adding new icons unrelated to core functionality at this time.

Thank you,
-Tracy
