### ISSUE TITLE
"Broken link" dashicon (dashicons-editor-unlink) could be more intuitive

### ISSUE THREAD

**Issue by Presskopp** [WordPress/dashicons#129]
In my eyes the broken link 'symbol' is not very intuitive. I'd go for something more like:

http://www.iconsdb.com/orange-icons/broken-link-icon.html

https://core.trac.wordpress.org/attachment/ticket/37246/broken-link-64.png

![broken-link-64](https://cloud.githubusercontent.com/assets/18373563/17375963/ab737382-59b3-11e6-890d-a7425f9acac7.png)

**Comment by TheTracyL** [comment]
Hello @Presskopp,

Thank you for the feedback, however we don't have any plans on iterating on this icon at this time.

-Tracy

**Comment by Presskopp** [comment]
This has been discussed for the welcome screen of WP 4.7 and it was changed a bit in the process. This thread here is a zombie meanwhile.
