### ISSUE TITLE
Round icons not centered

### ISSUE THREAD

**Issue by themeworm** [WordPress/dashicons#133]
Some of round icons (for example: admin-generic.svg, update.svg) not centered, you can see that when add rotation to icon

https://www.dropbox.com/s/e89kzaxppiu83tr/icon.PNG

**Comment by TheTracyL** [comment]
Hello,

Can you please provide a screen shot with a grid so we can see what you are explaining?

Thank you,
-Tracy

**Comment by field2** [comment]
There's no way to center the icon without a new design, since it must align to a 20x20 pixel grid and it's an odd pixel number width/height.
