### ISSUE TITLE
More popular social media icons (Instagram, LinkedIn Pinterest, Tumblr, WhatsApp)

### ISSUE THREAD

**Issue by xaliber** [WordPress/dashicons#136]
[Per this article in about.com](http://webtrends.about.com/od/socialnetworkingreviews/tp/Social-Networking-Sites.htm), I'm requesting more popular social media icons such as mentioned above. Would be very beneficial.

[Someone else has requested WhatsApp icon](https://github.com/WordPress/dashicons/issues/134) prior, and I'm +1-ing the request.

**Comment by hmm14e** [comment]
bump

**Comment by melchoyce** [comment]
Hi there, have you considered using http://fontawesome.io/icons/? We're not currently planning on adding more social icons to Dashicons.
