### ISSUE TITLE
Dashicons not working after changing wordpress URL

### ISSUE THREAD

**Issue by ellasravani** [WordPress/dashicons#137]
Hi,

Dashicons are not showing up in my website after changing the site address URL in wordpress.

Tried to enqueue the following. But no luck.
Kindly guide me to resolve the issue.

``` php
<?php
add_action( 'wp_enqueue_scripts', 'mytheme_scripts' );

function mytheme_scripts() {
    wp_enqueue_style( 'dashicons' );
}
```

NOTE: It is working fine in Safari browser but not in Chrome/firefox

**Comment by TheTracyL** [comment]
Hello @ellasravani 

Are you still experiencing this problem or did it resolve itself?

Thank you,
-Tracy

**Comment by TheTracyL** [comment]
If you are still experiencing this issue, please reopen the ticket and we will try to help.

Thank you,
-Tracy
