### ISSUE TITLE
Icon Request - Bone

### ISSUE THREAD

**Issue by darrenfulton** [WordPress/dashicons#138]
Hi, please add two "bone" icons that looks similar to the image in the URL below AND make one that is "-filled" and one that is "-empty" like the star icon.  Thanks!  
http://vignette1.wikia.nocookie.net/clubpenguin/images/d/d1/PuffleParty2014DogBiscuitBoneEmote.png/revision/latest?cb=20140421082841

**Comment by TheTracyL** [comment]
We are very sorry, but we are not adding new icons unrelated to core functionality at this time.

Thank you,
-Tracy
