### ISSUE TITLE
Dashicons Icon Picker Extension

### ISSUE THREAD

**Issue by talentedaamer** [WordPress/dashicons#144]
I have created a free opensource chrome extension for dashicons only. I want this to be included in WordPress resources page.

https://chrome.google.com/webstore/detail/dashicons-icon-picker/aaiglkcminbchhdjomkhpaikelfhekfo/

**Comment by field2** [comment]
Cool, how do I do that?

**Comment by TheTracyL** [comment]
Hello @talentedaamer 

Thank you for making us aware of this extension. Unfortunately, we will not be adding it to our resources page at this time.

-Tracy
