### ISSUE TITLE
Gun icons?

### ISSUE THREAD

**Issue by TodaysWeapons** [WordPress/dashicons#150]
Hi.  I just set up my site:  social.todaysweapons.com and was setting up my services page.  I was hoping for some sort of concealed weapons, pistol, rifle and shotgun icons as well as maybe some sporting clays or shooting sports icons.  Would you happen to know where those might be available?  Thanks.

**Comment by TheTracyL** [comment]
We are very sorry, but we are not adding new icons unrelated to core functionality at this time.

Thank you,
-Tracy
