### ISSUE TITLE
Main CSS file has Git merge data in it

### ISSUE THREAD

**Issue by engelen** [WordPress/dashicons#151]
See https://github.com/WordPress/dashicons/blob/master/css/dashicons.css. There's still some Git merge data in there :-).

```
<<<<<< HEAD
  [..] format('woff'),
=======
  [..] format('woff'),
>>>>>>> 4371e61db9f155084c12d71c50dac3023eb4273f
```

**Comment by TheTracyL** [comment]
This has been resolved.

Thank you,
-Tracy
