### ISSUE TITLE
Icon Request: REST API

### ISSUE THREAD

**Issue by Kenshino** [WordPress/dashicons#152]
It's for DevHub - https://developer.wordpress.org/

A little bite late for 4.7 but they can use a temporary icon for now.

**Comment by circlecube** [comment]
What about something like the image in this: http://v2.wp-api.org/assets/images/banner.jpg

**Comment by kadamwhite** [comment]
@circlecube That graphic has been in use for both the REST API project and auxiliary projects like [node-wpapi](https://twitter.com/kadamwhite/status/804346625896419332) and has influenced the branding of the [Day of REST events](http://feelingrestful.com), and I'm a fan, but I think we should look at it for its strengths rather than adopt it without discussion.

In that regard the current icon I like for its emphasis on linking nodes, which is what the REST API does -- allow remote communication more easily than ever before. Is there a more iconographic way we could portray that?

**Comment by kadamwhite** [comment]
From @rmccue in Slack:

> The connected-dots icon is what we’ve been using for a while, and it’s also in the 4.7 release post: https://wordpress.org/news/2016/12/vaughan/
>
> It’s originally from Iconic: https://useiconic.com/icons/connections/ (edited)
>
>
> However, worth mentioning that Iconic is _not_ open source: https://useiconic.com/license/
>
> Something in a similar vein of connected nodes would be the best, IMO

**Comment by TheTracyL** [comment]
@melchoyce @field2 Is this a valid reason for a new Dashicon? If so, we should make a trac ticket for it. I can take a stab at design if we want to add it.

**Comment by field2** [comment]
We should make a new Dashicon if it's going to be seen in the context of other ones, like in https://developer.wordpress.org/ so we should open the ticket and get it added in. 
There have been a ton of new icon requests that are in limbo until we sort out how to handle them within the new SVG sprite system, but this one (and maybe others?) are pretty critical to get them added  in.
@TheTracyL please open the ticket, stab away at the design and send me the vector file when you're done!

**Comment by field2** [comment]
I agree that it should be connected dots if we've already been using that. If we tweak the positioning of the connected dots, maybe a bit bigger or smaller, we should be outside of any license concerns.

**Comment by TheTracyL** [comment]
I'll make the ticket :-)

**Comment by TheTracyL** [comment]
Ben, let me know if there are any others that you see as critical and should be added.

**Comment by TheTracyL** [comment]
https://core.trac.wordpress.org/ticket/39296

**Comment by jaymanpandya** [comment]
Hi Team,

While I am new to this contribution, I have made one DashIcon for this. Please give feedback for the same. 

Thank you
Jayman
[rest api dashicon.zip](https://github.com/WordPress/dashicons/files/657094/rest.api.dashicon.zip)

**Comment by TheTracyL** [comment]
Hi Jaymen.

Feel free to participate on the trac ticket posted above. That is where Dashicon designs are reviewed and discussed.

Thank you!
-Tracy

**Comment by field2** [comment]
Icon added to latest version.

**Comment by TheTracyL** [comment]
This got lost. We are working on it again now.

**Comment by TheTracyL** [comment]
This is now added to Trac ticket: https://core.trac.wordpress.org/ticket/41074

**Comment by field2** [comment]
Fixed with https://github.com/WordPress/dashicons/commit/cc333651e31b9cd08bd2af932070a3859c2c4cfc
