### ISSUE TITLE
Please add new icon for us

### ISSUE THREAD

**Issue by kunjalfitgenie** [WordPress/dashicons#153]
We need the following icon, can you please create/add it to your list .. Or can we download the icon and us it in your plug-in??
Icon : https://www.iconfinder.com/icons/103796/view_icon#size=128..

**Comment by TheTracyL** [comment]
Hello.

There is already a visibility Dashicon: https://developer.wordpress.org/resource/dashicons/#visibility

Thank you!
-Tracy

**Comment by kunjalfitgenie** [comment]
Hello,

Thank you for quick reply.. The visibility icon is a little different than
our requirement, so I would request u to add the opaque eye image in the
list, so we can use it in your plugin

Kunjal
