### ISSUE TITLE
Icon Request: Social media icons

### ISSUE THREAD

**Issue by atsouf** [WordPress/dashicons#155]
Helo,

i was hoping for instagram, linkedin, youtube, skype, blogspot etc

Thanks in advance
Atsouf

**Comment by carterbeatsthedevil** [comment]
Agreed - a correct YouTube icon is a pretty big omission as it currently stands. I am happy to create/provide some options if that would help speed things along?

**Comment by TheTracyL** [comment]
Hello @atsouf 

We are very sorry, but we are not adding new icons unrelated to core functionality at this time.

Thank you,
-Tracy
