### ISSUE TITLE
New Dashicon

### ISSUE THREAD

**Issue by Marshallsbest** [WordPress/dashicons#157]
These are some that I've been needing, Basically  , the dolly for Overstock (Wholesale? , Moving?) , The programmers  icon, the dropper bottle for me it's Ejuice but can be used for more and the caliper for craftsmen.  

![ejuice whole sale](https://cloud.githubusercontent.com/assets/17542551/21979198/ee4b93cc-dbab-11e6-9ebe-0605c1451a82.png)
![pump truck](https://cloud.githubusercontent.com/assets/17542551/21979201/ee523704-dbab-11e6-811c-850c41579c59.png)
![artisan_flat - copy](https://cloud.githubusercontent.com/assets/17542551/21979200/ee4e2aa6-dbab-11e6-94d1-fbebed5865ac.png)
![dev material](https://cloud.githubusercontent.com/assets/17542551/21979199/ee4d833a-dbab-11e6-9537-91e7416dd8df.png)

**Comment by TheTracyL** [comment]
Hello @Marshallsbest 
We are very sorry, but we are not adding new icons unrelated to core functionality at this time.

Thank you,
-Tracy
