### ISSUE TITLE
Icon request: cart wp-r

### ISSUE THREAD

**Issue by mojwp** [WordPress/dashicons#159]
Our company [wp-r.ru](https://wp-r.ru/) will use this icon in our Wordpress themes, plugins and left admin menu.

![w](https://cloud.githubusercontent.com/assets/25607612/22775524/2139e12a-eebd-11e6-900c-ce691ef46def.png)
![logo_dark](https://cloud.githubusercontent.com/assets/25607612/22775525/213a6e88-eebd-11e6-9ab3-76eda1b4a669.png)

**Comment by field2** [comment]
@mojwp , you can make your own custom icons for that; they shouldn't be part of Dashicons.
[http://www.wpbeginner.com/wp-tutorials/how-to-add-icons-for-custom-post-types-in-wordpress/](There's a tutorial here) that may be useful.
