### ISSUE TITLE
new icon idea

### ISSUE THREAD

**Issue by micdech** [WordPress/dashicons#160]
I think is very helpful to have a new icon in dashicons for cook, cooking recipes and many other category enhaced to kitchen. My idea is to have an icon like the chef cook. Or a pot.

**Comment by TheTracyL** [comment]
Hello, @micdech 

We are very sorry, but we are not adding new icons unrelated to core functionality at this time.

However, we do have a carrot icon for food: https://developer.wordpress.org/resource/dashicons/#carrot
And an index card icon that can be used as a recipe card: https://developer.wordpress.org/resource/dashicons/#index-card 

Thank you,
-Tracy
