### ISSUE TITLE
Redesign 'Posts' icon

### ISSUE THREAD

**Issue by HardeepAsrani** [WordPress/dashicons#161]
Posts icon in Admin menu feels more like a Map Marker or Pin. It's not intuitive.

**Comment by nathanduckett** [comment]
It's a pin like you would use to pin up a post on a noticeboard.

**Comment by HardeepAsrani** [comment]
Sure, makes sense for some. But for most of people posts are articles.

**Comment by nathanduckett** [comment]
You could hook into the menu and swap the icon to any other dashicon see here that may help: https://wordpress.org/support/topic/change-default-posts-admin-icon-1/

**Comment by HardeepAsrani** [comment]
That I know. It was a request made in the dashicons meeting by me to be redesigned. Just my opinion/request for Dashicons, not demanding anything to be done. :p

**Comment by nathanduckett** [comment]
Ahhh ok fair enough :p

**Comment by OWMC** [comment]
I concur with everything HardeepArani has said here. It angers me greatly.

**Comment by field2** [comment]
Do you have any suggestions for a symbol for the posts icon?

**Comment by TheTracyL** [comment]
Hello @HardeepAsrani,

We appreciate your feedback, however we have no plans on changing the post icon at this time.

Thank you,
-Tracy

**Comment by HardeepAsrani** [comment]
*puts in his Seinfeld impression* Well, that's a shame. ;)
