### ISSUE TITLE
Social Media Icon Request

### ISSUE THREAD

**Issue by zaccety** [WordPress/dashicons#162]
I saw that it was decided not to include Instagram in dashicons in this ticket: https://core.trac.wordpress.org/ticket/34166

But I'd like to request a reconsideration, it makes sense to me to include all the popular social media channels, not just Twitter and Facebook, in the name of keeping the number of additional fonts needed for a site to a minimum.

**Comment by TheTracyL** [comment]
Hello @zaccety 

We are very sorry, but we are not adding new icons unrelated to core functionality at this time.

Thank you,
-Tracy
