### ISSUE TITLE
Icons not aligned to the center

### ISSUE THREAD

**Issue by brickbones** [WordPress/dashicons#165]
This are the icons that are not align to the center. I'm currently fixing all of the icons in this this list:

- admin-appearance.svg
- admin-comments.svg
- admin-generic.svg
- admin-home.svg
- admin-links.svg
- admin-multisite.svg
- admin-page.svg
- admin-settings.svg
- arrow-down.svg
- arrow-up.svg
- art.svg
- awards.svg
- backup.svg
- camera.svg
- cart.svg
- chart-pie.svg
- clipboard.svg
- cloud.svg
- editor-bold.svg
- editor-customchar.svg
- editor-ol.svg
- editor-outdent.svg
- editor-removeformatting.svg
- editor-textcolor.svg
- editor-ul.svg
- editor-underline.svg
- editor-unlink.svg
- email-alt.svg
- email.svg
- flag.svg
- format-quote.svg
- format-video.svg
- googleplus.svg
- groups.svg
- hammer.svg
- hidden.svg
- image-crop.svg
- laptop.svg
- location-alt.svg
- palmtree.svg
- performance.svg
- plus.svg
- redo.svg
- smiley.svg
- sticky.svg
- store.svg
- tagcloud.svg
- testimonial.svg
- thumbs-down.svg
- thumbs-up.svg
- tickets-alt.svg
- tickets.svg
- translation.svg
- trash.svg
- undo.svg
- uniF143.svg
- universal-access.svg
- video-alt.svg
- video-alt3.svg
- visibility.svg
- welcome-comments.svg
- welcome-view-site.svg
- welcome-widgets-menus.svg
- yes.svg

**Comment by field2** [comment]
Hi @brickbones , could you possibly explain how the issue fixes a specific problem? Are the icons off-center in the context of wp-admin? Please post any screenshots that may help us see the issue.

**Comment by TheTracyL** [comment]
Hi @brickbones ,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
