### ISSUE TITLE
Licence Clarification for Single Icons

### ISSUE THREAD

**Issue by tech4him1** [WordPress/dashicons#168]
Can I use the icon SVGs individually without releasing my code, as long as I don't change them?  Or is including only the ones I want, and combining them into a single file, considered a derivative?

**Comment by field2** [comment]
Great question! I believe that since Dashicons is licensed under GPL v.2, you can do anything you want with them as long as you keep the license in whatever you do release. You can even change them, and you don't have to release your code, you just have to include the license. But I'm no copyright lawyer, and I'd love to hear others chime in.

**Comment by tech4him1** [comment]
Me neither, and I've noticed that projects often have different interpretations of some of the details.  My original thought was:

If I take only the SVGs that I want and combine them (say with IcoMoon), does that fall under section 2b of the GPLv2 (quoted below)?  If so, do I need to explicitly release that file under the GPLv2, or just implicitly (if someone wants, they can reuse that file)?

> 2\. You may modify your copy or copies of the Program or any portion of it, thus forming a work based on the Program, and copy and distribute such modifications or work under the terms of Section 1 above, provided that you also meet all of these conditions:
>
> ...
>
> b) You must cause any work that you distribute or publish, that in whole or in part contains or is derived from the Program or any part thereof, to be licensed as a whole at no charge to all third parties under the terms of this License.

The font exception, though, says that (emphasis mine):

> As a special exception, if you create a document which uses this font, and embed this font or **unaltered portions of this font** into the document, this font does not by itself cause the resulting document to be covered by the GNU General Public License. This exception does not however invalidate any other reasons why the document might be covered by the GNU General Public License. If you modify this font, you may extend this exception to your version of the font, but you are not obligated to do so. If you do not wish to do so, delete this exception statement from your version.

I would think that the 'unaltered portions of this font' exemption would cover combining some of the SVGs into a single sprite file, but again, I'm not a lawyer either.

**Comment by tech4him1** [comment]
Another question: does the font exception also cover the use of the SVGs, or just the font, as it does not state explicitly, and if it doesn't, the whole program would have to be released under the GPL (see [GPLStaticVsDynamic on gnu.org](https://www.gnu.org/licenses/gpl-faq.en.html#GPLStaticVsDynamic)).  Could you add an exception stating that explicitly, or even better, do a dual licence under something like the Apache or SIL?

**Comment by desrosj** [comment]
Closing as this repo will be placed into archive state. See https://make.wordpress.org/core/2020/07/15/dashicons-in-wordpress-5-5-the-final-update/ for more information.
