### ISSUE TITLE
Wordpress icons

### ISSUE THREAD

**Issue by JoaoGabrielAquino** [WordPress/dashicons#181]
Give icons wordpress

**Comment by ntwb** [comment]
I'm not sure what you are asking for @JoaoGabrielAquino, could you try to explain it further please?

**Comment by TheTracyL** [comment]
Hello @JoaoGabrielAquino ,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you have more clarification, please reopen it and we will be happy to answer you.

Thank you!
-Tracy
