### ISSUE TITLE
Folder Icon

### ISSUE THREAD

**Issue by scorereviews** [WordPress/dashicons#195]
It would be wonderful if you guys could create a folder icon for the dashicon set.

**Comment by field2** [comment]
Is this what you're looking for? https://developer.wordpress.org/resource/dashicons/#category

**Comment by scorereviews** [comment]
That is exactly what I was looking for, but for some reason could not 
find it on the dashicons page.  Perhaps if the icons had labels on them 
instead of F-numbers (which are very confusing BTW).

Thanks so much for the rapid reply.

-James
