### ISSUE TITLE
it would be cool...

### ISSUE THREAD

**Issue by ukeboyska** [WordPress/dashicons#198]
if you could extend the icons w/fontawesome or another comparable icon font. that way you guys don't have to keep adding individual icons to the set, and devs can highly customize custom post types.

there's a plugin out there claiming to be able to do so, but it doesn't seem to work.

**Comment by field2** [comment]
Thanks for the suggestion. 
You can already add custom icons for your plugin. There are a few guides out there, but this one seems to be right:
https://wordpress.stackexchange.com/questions/172939/how-do-i-add-an-icon-to-a-new-admin-bar-item
We want to keep the style of the icons consistent. Adding new icons from another library goes against that.
