### ISSUE TITLE
Key

### ISSUE THREAD

**Issue by Ewaznazari** [WordPress/dashicons#208]
Key

**Comment by jwold** [comment]
@Ewaznazari are you wanting to add a different type of key other than what's already available?

Dashicons currently has this one: https://developer.wordpress.org/resource/dashicons/#admin-network

<img width="273" alt="screen shot 2017-06-26 at 7 30 01 am" src="https://user-images.githubusercontent.com/3411173/27544206-480deed2-5a41-11e7-8d56-f998a2fad173.png">
