### ISSUE TITLE
Crosshair Icon Request

### ISSUE THREAD

**Issue by safranck** [WordPress/dashicons#218]
![46x46_crosshair](https://user-images.githubusercontent.com/3579430/28083940-e7e16f42-662b-11e7-92fd-586e628649a5.png)

**Comment by field2** [comment]
Hi @safranck, we're not adding any new icons to Dashicons unless they're critical for new releases, so I'm closing this. Thank you for your design, I think it's well done and would be a good addition to the set once we start adding new ones.
