### ISSUE TITLE
Add focusable=false to the generated SVG markup (needed for Gutenberg)

### ISSUE THREAD

**Issue by afercia** [WordPress/dashicons#224]
Hello everyone. In Gutenberg, we've just merged a fix for an IE 11 bug, see https://github.com/WordPress/gutenberg/pull/2590

More details on the PR and the related issue https://github.com/WordPress/gutenberg/issues/1578

The fix is as simple as adding `focusable="false"` to prevent IE 11 giving focus to the icons.

I guess this fix should be ported here too 🙂

**Comment by field2** [comment]
Which file needs to be edited? I'm trying to figure out where focusable="false" goes...

**Comment by afercia** [comment]
At the end of the [react/index.jsx](https://github.com/WordPress/dashicons/blob/80aaf7d648d1286bda0d000fa2720dfd92239559/react/index.jsx#L828) file?

**Comment by field2** [comment]
This was fixed in a previous PR. Should be all set...

**Comment by afercia** [comment]
@field2 hi, unfortunately seems the following PR removed it: https://github.com/WordPress/dashicons/pull/226/files

there's no `focusable="true"` on master

**Comment by afercia** [comment]
Ping 🙂 This issue should be reopened.

**Comment by field2** [comment]
OK, added it again. Please review and make sure everything's up to date.

**Comment by afercia** [comment]
Thx! looks good!
