### ISSUE TITLE
create a new icon

### ISSUE THREAD

**Issue by broros** [WordPress/dashicons#232]
can you create a fire icon? or a flame icon?

**Comment by jaymanpandya** [comment]
Hi. 

Can we understand the requirement better. To help the conversation started I would propose below questions. 

What would be the purpose of this icon? 
Where will it be used? 
Does it have a potential of recurring usage to be included in Dashicons?

**Comment by field2** [comment]
Hi @broros,
We're not currently adding new icons to dashicons that aren't critical to core development.

**Comment by broros** [comment]
this icon will be used for bbpress to symbolize HOT topics, I think this icon will be very useful in the WordPress dashboard to symbolize hot posts, etc.
