### ISSUE TITLE
Blogspot Icon Request 

### ISSUE THREAD

**Issue by Sharjeeltahir58** [WordPress/dashicons#233]
I want Blogspot icon for my blog please add it like you are providing for WordPress. I provided the image example which you can use for the icon. 

Thanks

![67a6bfe51c07](https://user-images.githubusercontent.com/28932345/30405189-ee6f6d36-9903-11e7-81b3-ec875904b552.png)

**Comment by jaymanpandya** [comment]
Hi.

As @field2 noted in issue #232, we're not currently adding new icons to dashicons that aren't critical to core development.  

But still, can we understand the requirement better? It will help the team to take the decision on whether to include to tickets in any upcoming milestones. To help the conversation started I would propose below questions.

What would be the purpose of this icon?
Where will it be used?
Does it have a potential of recurring usage to be included in Dashicons?

Cheers
Jayman

**Comment by Sharjeeltahir58** [comment]
Hi jayman 

Thanks for replying.
 
This is a blogspot icon a platform like wordpress from google.  I am using dashicons for my menus in [sharjeeltahi.com](http://www.sharjeeltahir.com/) where i want to use this icon to tell readers that here they ll find blogspot tutriols. That's all i hope you understand.

**Comment by jaymanpandya** [comment]
Hi,

Dashicons is the official icon font of the "**WordPress admin area**". I am assuming you want to use the icon for the link that says "Blogger" on the top navigation in the front-end of your website. 

It won't be possible to add the Blogspot icon to the dashicons library as it is not related to the core development.

Cheers
Jayman

**Comment by Sharjeeltahir58** [comment]
Thank you so much for clarification :)
