### ISSUE TITLE
deshmenu

### ISSUE THREAD

**Issue by joy0152** [WordPress/dashicons#243]
![img](https://user-images.githubusercontent.com/29722762/31863329-213167c8-b76e-11e7-95be-f38e4f0da006.jpg)

**Comment by HardeepAsrani** [comment]
@joy0152 Can you include more details about why you have added the image? Do you want to suggest a new icon or want to improve an existing one, or is there any issue with one of the icons? :)

**Comment by joy0152** [comment]
![images](https://user-images.githubusercontent.com/29722762/31863490-d3b8cb24-b76f-11e7-979b-7aab30f9430c.jpg)

**Comment by joy0152** [comment]
I want to make it a new icon
