### ISSUE TITLE
Add Dashicon for Tide team

### ISSUE THREAD

**Issue by danieltj27** [WordPress/dashicons#248]
There is a new team on Make.WordPress.org called [Tide](https://make.wordpress.org/tide/). I had a look and there doesn't seem to be a suitable dashicon in place to use for that team and the most obvious one is a tidal icon.

I propose that something similar to the Emoji is used for this.

🌊 (_Tide Emoji_)

**Comment by field2** [comment]
This might be a case where adding another Dashicon is warranted. Let's get feedback on slack #design-dashicons

**Comment by MaximSiebert** [comment]
👋 hey guys, Maxim from XWP here – I've converted our Tide logo to a dashicon sized SVG for you guys to use!


[tide.svg.zip](https://github.com/WordPress/dashicons/files/1548522/tide.svg.zip)

**Comment by MaximSiebert** [comment]
Running into issues when trying to run `npm run build`. I've included the log file below if anyone can help me out 🙏 

[2017-12-11T17_29_50_566Z-debug.log](https://github.com/WordPress/dashicons/files/1548826/2017-12-11T17_29_50_566Z-debug.log)

**Comment by field2** [comment]
I there's something that has to be changed in your svg code. I compared it to the svgs in /source/svg changed it to have some of the same code as the preexisting ones, and the build worked. Unfortunately, whatever I did removed any shapes and tide.svg got converted to a blank square.

**Comment by field2** [comment]
It looks like the build process is particular about the formatting of the svg. I opened the tide icon in Illustrator, sized it to 20x20px , ungrouped it several times as it seems Figma grouped the shapes a few times, and exported the svg with these settings: 
![image](https://user-images.githubusercontent.com/1656980/34057265-416c278e-e1a4-11e7-937e-9ab2f77bf782.png)
This shows that we should provide working templates for figma and sketch files, but I'm still in the dark about what the difference is in the code.

**Comment by field2** [comment]
I was able to do `npm run build` with no errors on @jasmussen 's branch. I removed the tide.svg icon from /sources/svg and re-added the one posted to this issue, and tried `npm run build` and have the errors again.

**Comment by field2** [comment]
Sorry, didn't mean to close this until we decide if adding the icon is warranted

**Comment by jeffpaul** [comment]
@field2 who would decide if adding the icon is warranted?

**Comment by jeffpaul** [comment]
@field2 I'm going to go ahead and confirm that the icon is warranted as Tide is currently using a 'pin' icon on make.wordpress.org and Pascal Casier looking to setup a wordpress.org [profile badge](https://make.wordpress.org/meta/handbook/documentation/profile-badges/) that will need a dashicon as well. Assuming we move forward with creating the dashicon, what else is needed?

**Comment by field2** [comment]
OK, I can add it in.  We should update https://core.trac.wordpress.org/ticket/41074 to make it official.

**Comment by jeffpaul** [comment]
@field2 are you able to update the patch on 41074 or do we need @ntwb to help refresh the patch for 5.0?

**Comment by ntwb** [comment]
I've updated #41074 to reference this issue, once Tide is added we can test out the new build process and create a refreshed patch for 41074

**Comment by jeffpaul** [comment]
@ntwb thanks!

@field2 let me know what else is needed to commit the Tide dashicon so we can test the new build process and refresh the patch for 41074.

**Comment by jasmussen** [comment]
@jeffpaul I'll be around if need be, I did the initial work on the build process.

The short summary of it, the build process makes it feasible to continue using Dashicons, but the first time the new built files are merged in, the diff will be slightly bigger than it usually is. Quite simply, we can't get the built files to match the old manually edited CSS files perfectly. For example the old files had icons grouped, the new files have icons alphabetized. But it is worth it, we just need to test properly, so good to get in early.

More details in https://github.com/WordPress/dashicons/pull/246#issue-271453471 and the linked trac thread.

**Comment by cathibosco** [comment]
@jasmussen @dmaweb 
We have simplified the tide dashicon - it is clean and rendered to the correct proportions. Can it be merged into the repo now so it appears here: https://developer.wordpress.org/resource/dashicons/#wordpress

I also left the files in the slack channel a week or so ago - thanks so much!
[Tide-simplified.zip](https://github.com/WordPress/dashicons/files/2784636/Tide-simplified.zip)

**Comment by jasmussen** [comment]
I have a fair bit on my table so I won't be able to make a PR with the updated SVG in the near future. 

However we still don't have the new build process font files in WordPress, and 5.1 beta is already out. I wonder if we can still manage to get those in? @ntwb do you have insights or bandwidth into how we get that show on the road?

> https://developer.wordpress.org/resource/dashicons/#wordpress

I don't actually know how that page is updated. I could swear @ryelle  was involved.

**Comment by ryelle** [comment]
> I don't actually know how that page is updated.

It's a page template in the developer handbook theme: https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-developer/page-dashicons.php

**Comment by ntwb** [comment]
> However we still don't have the new build process font files in WordPress, and 5.1 beta is already out. I wonder if we can still manage to get those in? @ntwb do you have insights or bandwidth into how we get that show on the road?

I've some time this week and next to start going through Trac to clear _my_ backlog, I'll take a look at this and come up with a plan of attack and leave notes on the appropriate ticket/s

**Comment by field2** [comment]
I can add the new icon in today. It's been a while since I've done one, so bear with me...

**Comment by field2** [comment]
The new icon looks identical to the one in this repo, it's just in a 24x24 artboard instead of a 20x20 one currently there.
There isn't a tide icon in the Gutenberg directory. Should this icon go in there?
I can update the github repo, but I'd prefer if someone else does the trac patch.

**Comment by ntwb** [comment]
>  ... I'd prefer if someone else does the trac patch.

I should be able to handle that

**Comment by jeffpaul** [comment]
FYI that this was included in [WP 5.2](https://make.wordpress.org/core/2019/04/11/dashicons-in-wordpress-5-2/) and can be closed.

**Comment by jasmussen** [comment]
Thanks.
