### ISSUE TITLE
Grunt errors

### ISSUE THREAD

**Issue by field2** [WordPress/dashicons#253]
`npm run build` yields an error: 
```Fatal error: Invalid character in tag name
Line: 0
Column: 65
Char: <
```
Only seems to happen if an svg has been changed in /sources/svg.

**Comment by Zodiac1978** [comment]
Is this issue still valid?

**Comment by jasmussen** [comment]
I can't reproduce, and given things have changed a lot in the build process, I'm going to close for now!
