### ISSUE TITLE
Possible issue with Twitter glyph and the f301 code point in some browsers

### ISSUE THREAD

**Issue by Otto42** [WordPress/dashicons#254]
Issue reported here: 
https://meta.trac.wordpress.org/ticket/3352

On the dashicons resource page, the "Copy Glyph" function doesn't work properly in some browsers, but only for the f301 code point (the Twitter icon).

https://developer.wordpress.org/resource/dashicons/#twitter

I have no explanation for this, but perhaps f301 is being used for something else or is interpreted differently, somehow?

**Comment by Zodiac1978** [comment]
There are some explanations on the meta ticket now:
https://meta.trac.wordpress.org/ticket/3352#comment:13

Not sure about the possible solutions.

**Comment by desrosj** [comment]
Closing as this repo will be placed into archive state. See https://make.wordpress.org/core/2020/07/15/dashicons-in-wordpress-5-5-the-final-update/ for more information.
