### ISSUE TITLE
Beer Icon

### ISSUE THREAD

**Issue by ATLTEK** [WordPress/dashicons#256]
Please add a beer icon for WP.

**Comment by emaildano** [comment]
🍻

**Comment by Zodiac1978** [comment]
What would be the need of this icon in the WordPress admin area?

**Comment by field2** [comment]
If this works, @jasmussen can add in:
[beer-icon.svg.zip](https://github.com/WordPress/dashicons/files/4387540/beer-icon.svg.zip)
![Screen Shot 2020-03-26 at 9 57 20 AM](https://user-images.githubusercontent.com/1656980/77655030-3a9e4200-6f48-11ea-93b4-99e3fedc5a44.png)
![Screen Shot 2020-03-26 at 9 57 54 AM](https://user-images.githubusercontent.com/1656980/77655067-4ab62180-6f48-11ea-8d38-358bcd751c35.png)

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
