### ISSUE TITLE
Suggested improvements to the "plus" and "minus" icons.

### ISSUE THREAD

**Issue by dsifford** [WordPress/dashicons#257]
Hi there,

I have a couple quick suggestions for improving the `plus` and `minus` icons that I was hoping to run past you all.

### Suggestion 1

**Issue**: The horizontal bar of the plus icon is much thicker than the minus icon. To me, this looks strange if you place the icons next to each other (example 1).

**Suggested Change:** Increase the thickness of the minus icon to be the same thickness as the horizontal bar of the plus icon.

![image](https://user-images.githubusercontent.com/5240018/34547642-a5944112-f0ca-11e7-8945-df2b4605f275.png)

### Suggestion 

**Issue**: The plus icon is not centered vertically within its visual area (example 2), which ends up placing the icon slightly higher than the minus icon.

**Suggested change**: Center the icon.

![image](https://user-images.githubusercontent.com/5240018/34547732-58a268a6-f0cb-11e7-8ea4-1177b2564a4b.png)

-----

Thanks for considering. I'm happy to submit a PR for these changes if you all agree that these changes should be made.

**Comment by field2** [comment]
Hi @dsifford ,
Thanks for your suggestions. We've discussed the off-center plus before:
https://core.trac.wordpress.org/ticket/31506
https://github.com/WordPress/dashicons/issues/118

There's not much we can do about this, given the 3px width of the plus and the fact that dashicons is 20x20, so the icon would need to be 2px or 4px wide to be centered.

I think the minus could be 3px wide, but it may be used in some contexts where that would be too thick. It would help to see screenshots of how the admin would look with your edits though.

**Comment by dsifford** [comment]
@field2 Gotcha.

Is `plus-alt` 4px wide? That looks perfectly acceptable to me. What was the team's thoughts on just making the plus 4px wide?

Benefit in doing that would be that it would be uniform with the other plus icons.

I think a 4px wide minus would also be acceptable. Curious to hear your thoughts.

**Comment by Zodiac1978** [comment]
@field2 @dsifford This discussion ends very abruptly. Is this resolved?

**Comment by field2** [comment]
[plus-minus-3px.zip](https://github.com/WordPress/dashicons/files/4387675/plus-minus-3px.zip)
![Screen Shot 2020-03-26 at 10 08 49 AM](https://user-images.githubusercontent.com/1656980/77656192-e300d600-6f49-11ea-9ad4-f514edc71fb2.png)
![Screen Shot 2020-03-26 at 10 05 12 AM](https://user-images.githubusercontent.com/1656980/77656194-e3996c80-6f49-11ea-8843-6003270bf4e1.png)
These are 3px wide and centered. The horizontal edges are going to be blurry on low-dpi screens, but at this point it's not as big a concern as it once was maybe.

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
