### ISSUE TITLE
New icon for WordPress Coding Standards (WPCS)

### ISSUE THREAD

**Issue by mapk** [WordPress/dashicons#263]
There is a request for a new icon for WordPress Coding Standards. 

Request was made here by @gamajo 
https://meta.trac.wordpress.org/ticket/3377#comment:6

It will be displayed on this page here:
https://meta.trac.wordpress.org/ticket/3377#comment:5

**Comment by ntwb** [comment]
There's an ongoing discussion on WPCS for a new icon here:
> https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/540

**Comment by field2** [comment]
Trac is updated with new icon proposal : https://meta.trac.wordpress.org/ticket/3377#comment:13

**Comment by cathibosco** [comment]
I updated the new icon proposal: It is much cleaner - I was able to adjust it based on the template with guidelines etc...

[Archive 2.zip](https://github.com/WordPress/dashicons/files/1732808/Archive.2.zip)

**Comment by jrfnl** [comment]
Just wondering what the current status is... Any updates ? Anything we can do to move this forward ?

**Comment by ntwb** [comment]
@jrfnl I'd hoped it would have been included in the dashicons update that just landed for 5.2, but it looks like it was missed, seeking clarification on that now via https://core.trac.wordpress.org/ticket/41074#comment:107

**Comment by cathibosco** [comment]
Here is the simplified (cleaner) .ai and .svg file that can be used to merged this in today.

Thank you for not letting it slip through the cracks  :)
[code-standards-simplified.zip](https://github.com/WordPress/dashicons/files/3008243/code-standards-simplified.zip)

**Comment by desrosj** [comment]
Hmm, when I try to add this icon to the font, I am seeing the following:

```
Fatal error: Unexpected close tag
Line: 0
Column: 787
Char: >
```

**Comment by desrosj** [comment]
Thanks @jasmussen for figuring out what my issue was. For information, please check the #353 PR that added this icon.

This was merged to Core in [changeset-45040](https://core.trac.wordpress.org/changeset/45040).

**Comment by jrfnl** [comment]
Awesome! Thank you all!
