### ISSUE TITLE
Dashicon for Mobile,Website,Fax.

### ISSUE THREAD

**Issue by rishimaurya** [WordPress/dashicons#266]
I need Dashicons for Mobile, Website, and Fax.

**Comment by Zodiac1978** [comment]
For mobile there is:
https://developer.wordpress.org/resource/dashicons/#smartphone
(Tablet has: https://developer.wordpress.org/resource/dashicons/#tablet )
Website:
https://developer.wordpress.org/resource/dashicons/#laptop
or
https://developer.wordpress.org/resource/dashicons/#desktop

I am not sure how important fax really is in our modern times.

**Comment by field2** [comment]
Closing this as alternatives exist and I can picture how a fax icon would look or if it would be recognized. I will reopen if anyone still wants it though.
