### ISSUE TITLE
.dashicons-buddicons-buddypress-logo not included

### ISSUE THREAD

**Issue by hive-4-apps** [WordPress/dashicons#267]
I tried to use the css class .dashicons-buddicons-buddypress-logo, it does not show the icon.
`<a href="#" class="dashicons-before dashicons-buddicons-buddypress-logo">My link</a>`
Is it included in the native 4.93 wordpress version ?

**Comment by ntwb** [comment]
They are not included in WordPress 4.9.3, they will be included in WordPress 5.0 via [#WP41074](https://core.trac.wordpress.org/ticket/41074)

p.s. This issue can be closed per the above.

**Comment by shresthabiswas** [comment]
Not working in 5.1.1 version
