### ISSUE TITLE
Printer icon

### ISSUE THREAD

**Issue by x-moe-x** [WordPress/dashicons#268]

**Comment by toonvandeputte** [comment]
Proposed icon:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/6859906/36908006-62be93cc-1e3a-11e8-852a-465d1bae7436.png">

**Comment by x-moe-x** [comment]
Awesome!

**Comment by Zodiac1978** [comment]
PR in #389

**Comment by field2** [comment]
![Screen Shot 2020-03-26 at 10 22 20 AM](https://user-images.githubusercontent.com/1656980/77657458-b5b52780-6f4b-11ea-9efd-c159a0a001f2.png)
![Screen Shot 2020-03-26 at 10 22 05 AM](https://user-images.githubusercontent.com/1656980/77657460-b5b52780-6f4b-11ea-86c8-4ce6778da2a3.png)
[printer.svg.zip](https://github.com/WordPress/dashicons/files/4387778/printer.svg.zip)
This can be added in

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
