### ISSUE TITLE
Can we get a coffee bean or mug/cup icon?

### ISSUE THREAD

**Issue by televators** [WordPress/dashicons#270]
After setting up a coffee-related plugin with a custom Coffee post type, I realized there's no suitable icon for it! It seems like any icon set should have coffee since it is one of the main resources used in creating art and code. Just sayin'.

Thanks for any consideration! Peace.

**Comment by field2** [comment]
[coffee.svg.zip](https://github.com/WordPress/dashicons/files/4388689/coffee.svg.zip)
![Screen Shot 2020-03-26 at 1 14 34 PM](https://user-images.githubusercontent.com/1656980/77675828-d4bfb380-6f63-11ea-97ea-0490f3913cbc.png)
![Screen Shot 2020-03-26 at 1 14 20 PM](https://user-images.githubusercontent.com/1656980/77675831-d4bfb380-6f63-11ea-8656-95725f0d7fd4.png)
These can be added

**Comment by seezee** [comment]
In the meantime, I'm using Font Awesome's icon. But it would be better if there was a native (Dashicon) version of this.

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
