### ISSUE TITLE
Alternate Globe Icons

### ISSUE THREAD

**Issue by desrosj** [WordPress/dashicons#275]
The `dashicons-admin-site` icon is an American focused globe. Something I noticed on Facebook recently is that the globe icon changes based on your location.

It would be cool if there were a few other alternate globe icons. Maybe one focused on Europe/Africa, and one focused on Asia/Australia.

**Comment by toonvandeputte** [comment]
Currently at WordCamp Antwerp Contributor Day and having a look at this.

**Comment by toonvandeputte** [comment]
Apparently, these icons already exist:

* Glyph 15 - U+F11D - admin-site-alt.svg (focus on Europe/Africa)
* Glyph 16 - U+F11E - admin-site-alt2.svg (focus on Asia)
* Glyph 17 - U+F11F - admin-site-alt3.svg (generic globe with meridians)

**Comment by field2** [comment]
They do, although they may not be in the current version of dashicons in trunk. Either way, they'll be in the next release
