### ISSUE TITLE
Notification bell request

### ISSUE THREAD

**Issue by hedgefield** [WordPress/dashicons#281]
[There is talk of a notification center in WordPress](https://core.trac.wordpress.org/ticket/43484) that this would be useful for, but regardless it would be nice to have the bell icon from wordpress.com also available as a dashicon.

**Comment by benbodhi** [comment]
+1
I'm using the megaphone for now... because I want to stick with dashicons for, well... dashboard icons.
A bell would be amazing!

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77681030-27509e00-6f6b-11ea-972a-85797f994318.png)
![image](https://user-images.githubusercontent.com/1656980/77681091-3fc0b880-6f6b-11ea-8168-2dfe63848788.png)
[bell.svg.zip](https://github.com/WordPress/dashicons/files/4389036/bell.svg.zip)

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
