### ISSUE TITLE
TTF File wont install as regular font on Mac (Using fontBook)

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/dashicons#282]
I wanted to install the font on my Mac (using the standard FontBook app) so that I can use the icon in a meetup presentation, but the TTF wont install.

If I validate the font file using FontBook, it passes, but it still refuses to install.

**Comment by mynameiskyle** [comment]
Same thing is happening to me. Double clicking the font file did nothing. Going in to FontBook and adding it through their interface resulted in "Serious found with this font file. Do not install" which I did anyway and it still didn't work.

The documentation says to use the .otf font, which I don't believe exists any longer/

**Comment by field2** [comment]
I was able to install it. I downloaded it from the the repo, right-clicked, installed with Fontbook, and it loaded ok. Not sure what's different for you-I'm on MacOS 10.15.2

**Comment by mynameiskyle** [comment]
Thanks @field2, 

I've tried opening the file in FontBook a handful of ways. Just doesn't seem to fully install. I'm...still on Mojave somehow? Interesting. I'll try updating to see if that helps.

I appreciate the quick reply!

**Comment by jasmussen** [comment]
I can't reproduce:

![fontbook](https://user-images.githubusercontent.com/1204802/79743642-36760200-8305-11ea-8ec2-c2da50ddf723.gif)

So I'll close for now. We can reopen this if consistent steps to reproduce appear! Thanks!

**Comment by maddisondesigns** [comment]
I've just downloaded the fonts files again, and I was able to install it ok this time. I wouldn't think it should have anything to do with it, but I'm on Catalina now (10.15.4) whereas I would've been on Mojave when I raised this back in 2018.

**Comment by jasmussen** [comment]
The font has been rebuilt a couple of times since then also, so it's possible it was broken at one point.
