### ISSUE TITLE
Wiki icon request

### ISSUE THREAD

**Issue by SeanDS** [WordPress/dashicons#284]
Hi, first of all, great work designing such lovely icons!

I'd like to request a dashicon that is basically the "pages" icon but with a pen or pencil on top of it, to represent a wiki page post type. Right now I'm using the [welcome-write-blog](https://developer.wordpress.org/resource/dashicons/#welcome-write-blog) icon to achieve something similar, but since my "wiki" page type is closely related to core pages, I'd like to use the same base icon as pages but with the addition of something to show it is "publicly editable".

Cheers!

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77682352-2fa9d880-6f6d-11ea-8057-15f9efeb8e10.png)
[edit-page.svg.zip](https://github.com/WordPress/dashicons/files/4389098/edit-page.svg.zip)

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!

**Comment by SeanDS** [comment]
Thanks!
