### ISSUE TITLE
Icon request: Business Woman and/or Business Person

### ISSUE THREAD

**Issue by nate-allen** [WordPress/dashicons#285]
Currently, there is a "businessman" icon, and I use it a lot for custom post types like bios, team members, job postings, etc. 

I work in the nonprofit space and it's pretty embarrassing having to explain to a woman's rights organization why they would have to pay extra for a custom female icon because WordPress only offers a male version.

Adding a business woman icon is a good solution. Adding a gender neutral business person icon would be even better.

**Comment by cathibosco** [comment]
Yes! We are so glad you asked for it... we can do some professional inclusive design(s). I’ll Offer up a design or two for review.👩🏽‍💻

**Comment by nate-allen** [comment]
That would be great, thank you! If there's anything I can do to help, just let me know.

**Comment by Zodiac1978** [comment]
As there is now a businesswoman and a businessperson I close this issue as resolved.

**Comment by airplanenoise** [comment]
I have to say that the businessperson looks a lot like the businessman, but not am not sure how to solve that... we've opted to use businesswoman every time that someone used businessman :)
