### ISSUE TITLE
new icons request

### ISSUE THREAD

**Issue by pbiron** [WordPress/dashicons#291]
I have a need in a plugin I'm writing for icons representing "database" and "database table".  It would be really great if there were dashicons for these.

My current "stopgaps" are to use `dashicons-admin-home` for "database" (since the database in question is for the WP db for the site the plugin is active in) and `dashicons-editor-table` for "database table".

Design suggestions: typically databases are represented a 3 stacked cylinders and database tables as something akin to a typical "spreadsheet" icon.

If the general idea behind this request is accepted, it would probably also be good to also add dashicons for operations on databases, e.g. "import", "export", "delete", etc.  As for design suggestions for those operations, see the 1st couple of rows at  [Database Icons](https://icons8.com/icon/set/database/office).

**Comment by field2** [comment]
Well, in any case, here they are:
[Archive 3.zip](https://github.com/WordPress/dashicons/files/4389478/Archive.3.zip)
![Screen Shot 2020-03-26 at 3 21 15 PM](https://user-images.githubusercontent.com/1656980/77687927-99c67b80-6f75-11ea-8e59-b3f018b68d22.png)
![Screen Shot 2020-03-26 at 3 20 52 PM](https://user-images.githubusercontent.com/1656980/77687929-9a5f1200-6f75-11ea-8aa0-aa4852886f0c.png)
![Screen Shot 2020-03-26 at 3 20 40 PM](https://user-images.githubusercontent.com/1656980/77687930-9a5f1200-6f75-11ea-9f92-4665d4c40ff9.png)
![Screen Shot 2020-03-26 at 3 20 22 PM](https://user-images.githubusercontent.com/1656980/77687931-9a5f1200-6f75-11ea-8b13-4994b42b30cc.png)
![Screen Shot 2020-03-26 at 3 20 04 PM](https://user-images.githubusercontent.com/1656980/77687932-9a5f1200-6f75-11ea-82a3-acfdf39e3a74.png)

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
