### ISSUE TITLE
Wrapkit Wordpress Icons

### ISSUE THREAD

**Issue by saber-salhi** [WordPress/dashicons#292]
i want to use the official icon font of the WordPress admin  in my own template

**Comment by Zodiac1978** [comment]
> i want to use the official icon font of the WordPress admin in my own template

You can load the dashicons in the frontend too:

```
function include_dashicons_font() {
    // Loading Dashicons font
    wp_enqueue_style('dashicons');
}
add_action( 'wp_enqueue_scripts', 'include_dashicons_font', 100 );
```

Then you can use it like this:
`<span class="dashicons dashicons-tickets"></span>`
