### ISSUE TITLE
Aeroplane

### ISSUE THREAD

**Issue by VinceGledhill** [WordPress/dashicons#294]
Please can I have an aeroplane as a dashicon icon?

**Comment by Zodiac1978** [comment]
What would be the need of this icon in the WordPress admin area?

**Comment by field2** [comment]
[airplane.svg.zip](https://github.com/WordPress/dashicons/files/4389631/airplane.svg.zip)

![image](https://user-images.githubusercontent.com/1656980/77690641-ff1c6b80-6f79-11ea-99bd-36f355080446.png)

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
