### ISSUE TITLE
Request for new dashicon for 'Visual Inspector by CanvasFlip'

### ISSUE THREAD

**Issue by manish1988** [WordPress/dashicons#295]
Hey guys, 

I'm Manish, maker of popular design tool - Visual Inspector - a Chrome extension for non designers to make changes to live website and collaborate remotely. VI is being used by more than 40,000 designers around the world to edit 3,00,000 website every month.

We have built a WordPress plugin, to push changes into external style.css made via Visual Inspector without putting the efforts to copy and pasting the code. 

I need Visual Inspector logo added in WP Dashicons to create seamless experience for our users. We are attaching icon to be added in PNG.

![logo_inspector_32x32](https://user-images.githubusercontent.com/2286697/39186093-f9771930-47e6-11e8-8ca4-fde97d0217c4.png)

For further query/clarification, please drop a note to me at Manish@canvasflip.com 

@Manish
Co-founder & CTO, 
CanvasFlip Inc

**Comment by jaymanpandya** [comment]
Hey Manish,

Addition of new icons is on hold as of now unless they are needed for core purposes. This can be done something in future.

@field2 : Please re-assign the appropriate status to this ticket when you can. :)

**Comment by field2** [comment]
Closing for now.
