### ISSUE TITLE
REQUEST: Wechat dashicon, Material vertical dots dashicon

### ISSUE THREAD

**Issue by lijitimit** [WordPress/dashicons#297]
I absolutely love the fact that dashicons are built into the wordpress system.  My main site is located in China, so trying to load resources from outside the great wall (like fontAwesome) is problematic, dashicons solves that!

I'd like to request two dashicons to add to the list:
1.  Google's material design "3 vertical dot" menu.
2.  WeChat logo (#1 social media site with hundreds of millions of users)

Thanks guys!

**Comment by jaymanpandya** [comment]
Hi,

New icons are not added as of now unless they are needed for core purposes. This can be done in future.

**Comment by lijitimit** [comment]
Ok, thanks for the reply!  There's some text on the second paragraph
https://developer.wordpress.org/resource/dashicons/#products

That reads:
For new icon requests, please create a new issue on the Dashicons github
<https://github.com/WordPress/dashicons/issues/new?labels=request>.

You may wish to remove it or modify it to say "new CORE icon requests" if
you want to stop receiving these kind of tickets.   Appreciate your hard
work!
James

**Comment by jaymanpandya** [comment]
Hey James,

I want to clarify that adding icons is stopped as of now cause of some priorities but we might be able add this in future. 

Thank you for putting in the request. Such requests helps WordPress to become better by the day. :)

Cheers
Jayman

**Comment by field2** [comment]
[wechat-logo.svg.zip](https://github.com/WordPress/dashicons/files/4389668/wechat-logo.svg.zip)

![image](https://user-images.githubusercontent.com/1656980/77691360-21fb4f80-6f7b-11ea-93d0-e66ae459a0e9.png)

Here it is if we need it. Thanks for the post, sorry for the late reply!

**Comment by lijitimit** [comment]
Nice one!  Thank you
