### ISSUE TITLE
No package release on GitHub

### ISSUE THREAD

**Issue by melvinstanly** [WordPress/dashicons#306]
[This package](https://www.jsdelivr.com/package/gh/melchoyce/dashicons) doesn't have any [GitHub release](https://help.github.com/articles/about-releases/). Could you please create one, so that people can use this project from jsDelivr CDN?

**Comment by ntwb** [comment]
Thanks @melvinstanly, I don't see this repo releasing a new version until v1 is ready and I expect this will coincide with WordPress 5.0 and Gutenberg.

For now I'd suggest you use a commit hash as documented on: 
> https://www.jsdelivr.com/package/gh/wordpress/dashicons
> https://cdn.jsdelivr.net/gh/wordpress/dashicons@5c3b4875eaf3216ee25c4976f5a49434c28aa3fd/

**Comment by melvinstanly** [comment]
@ntwb Thanks for the information.

**Comment by Zodiac1978** [comment]
@melvinstanly @ntwb Can I close this issue here? Or should this stay open for some reason?

**Comment by melvinstanly** [comment]
You can close this. Thank you
