### ISSUE TITLE
Instagram Icon

### ISSUE THREAD

**Issue by adyygupta** [WordPress/dashicons#308]
Please generate instagram icon

**Comment by jeffpaul** [comment]
@adyygupta that's been merged into the repo ([see closed PRs here](https://github.com/WordPress/dashicons/pulls?q=is%3Apr+instagram+is%3Aclosed)), but in order for them to appear on the Dashicons site we need to get https://core.trac.wordpress.org/ticket/41074 committed (which will fingers crossed happen this week in time for WordPress 5.2 beta).
