### ISSUE TITLE
LinkedIn icon

### ISSUE THREAD

**Issue by j0lee** [WordPress/dashicons#309]
Hi, please create a Linked In social icon. Thank you!

**Comment by rdiepenbrock** [comment]
I second this. LinkedIn dashicon is needed. Thank you!

**Comment by ThessaV** [comment]
A Linkedin-icon would indeed be very helpful!

**Comment by franworks** [comment]
Agreed

**Comment by suresh-shinde-engineer** [comment]
Hello Team, please add a Linked In social icon. It is very useful.

Thank you!

**Comment by AlexandreLefran** [comment]
I second this too. Is it possible to add the LinkedIn icon please?

**Comment by field2** [comment]
[linkedin.svg.zip](https://github.com/WordPress/dashicons/files/4393776/linkedin.svg.zip)
![image](https://user-images.githubusercontent.com/1656980/77761646-bebafd00-700e-11ea-9063-7740ccf8e11a.png)

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
