### ISSUE TITLE
Pets

### ISSUE THREAD

**Issue by eruotolo** [WordPress/dashicons#310]
[paw-solid.pdf](https://github.com/WordPress/dashicons/files/2237262/paw-solid.pdf)

**Comment by eruotolo** [comment]
![paw-solid](https://user-images.githubusercontent.com/9631426/43346906-7ec4e096-91c9-11e8-8454-9f9286a331c9.png)

**Comment by Zodiac1978** [comment]
What would be the need of this icon in the WordPress admin area?

**Comment by field2** [comment]
Optimized for dashicons. 
[pets.svg.zip](https://github.com/WordPress/dashicons/files/4393781/pets.svg.zip)
![image](https://user-images.githubusercontent.com/1656980/77761866-0d689700-700f-11ea-8ed6-2d0a2347f917.png)

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
