### ISSUE TITLE
Color picker needed for Gutenberg

### ISSUE THREAD

**Issue by postphotos** [WordPress/dashicons#313]
Related:
https://github.com/WordPress/gutenberg/issues/5258#issuecomment-403778155

The current proposal for this related ticket requires a new item (color eyedropper) added to Dashicons.

**Comment by field2** [comment]
Working on it...

**Comment by field2** [comment]
How's this:
![image](https://user-images.githubusercontent.com/1656980/43971343-a86c8c7a-9c9e-11e8-9c07-1c522b7cac2b.png)


![image](https://user-images.githubusercontent.com/1656980/43971333-9e9ce00a-9c9e-11e8-95c3-6cc106bc9ee1.png)

![image](https://user-images.githubusercontent.com/1656980/43971320-93e5129a-9c9e-11e8-9c87-9fa1fd0e3742.png)

**Comment by Zodiac1978** [comment]
After merging #314 this issue could be closed, or not @field2 ?

**Comment by field2** [comment]
We can close this.
