### ISSUE TITLE
Twitch Icon

### ISSUE THREAD

**Issue by triehle** [WordPress/dashicons#317]
Hey team!

I'm working on a plugin to display some twitch streams on our homepage and I've created a custom icon for Twitch to be used in the admin area, but it would be amazing if there were an actual Twitch dashicon so that I could use the image in a few other places.  

Thanks for your time!

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77762231-954ea100-700f-11ea-9425-a31671c58d24.png)
[twitch.svg.zip](https://github.com/WordPress/dashicons/files/4393807/twitch.svg.zip)

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
