### ISSUE TITLE
Requesting a new Money Icon

### ISSUE THREAD

**Issue by CanduriLuis** [WordPress/dashicons#318]
Hey there people from _Dashicons_! 

I'm starting to work with WordPress and you guys are the best when I need an icon for a custom post type, but right now I'm needing a money icon, something like a **Dollar sign** or a **Credit Card**, because I'm creating a post type for  **_"Credits"_** and none of the current icons fits that type.

Thank's in advance for the help you may provide and looking forward for the icon!

**Comment by masoodkord** [comment]
https://github.com/Wwwwordpresscom/daniyal-webstor/projects/1#card-12821080

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77763276-34c06380-7011-11ea-91e7-1d84677bc242.png)
[money.svg.zip](https://github.com/WordPress/dashicons/files/4393866/money.svg.zip)

**Comment by field2** [comment]
We should probably have symbols for a wider range of currencies, but this should be ok for now.

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
