### ISSUE TITLE
3D printers icon

### ISSUE THREAD

**Issue by Alil2096** [WordPress/dashicons#325]
Hi guys and very compliment for your work ;) 

Can you add some icons on 3d printer?

These image are only an examples:

https://www.123rf.com/photo_84294874_stock-vector-3d-printer-construct-icon-set-simple-set-of-9-3d-printer-construct-vector-icons-for-web-isolated-on-.html?fromid=NmxWcTlWYU1LRUxSc3JMNVJJNTgxZz09

https://www.123rf.com/photo_84367113_stock-vector-3d-computer-printer-icon-set-simple-style.html?fromid=NmxWcTlWYU1LRUxSc3JMNVJJNTgxZz09

Thanks very much :)

**Comment by Zodiac1978** [comment]
Dashicons have a unique goal: These icons should be used in the WordPress admin area. I think this topic "3D printer" is very specific and niche and not matching the scope of this iconset.
