### ISSUE TITLE
Gamer icons

### ISSUE THREAD

**Issue by qeamer** [WordPress/dashicons#328]
Hi!
I could have use for gaming icons for games like Pubg, cs, rocket league, headsets, mice, keyboard, screens, pc's, matches, teamwork for example. 
Also smaller versions would be nice.

**Comment by field2** [comment]
[games.svg.zip](https://github.com/WordPress/dashicons/files/4393966/games.svg.zip)
![image](https://user-images.githubusercontent.com/1656980/77764944-de085900-7013-11ea-90a2-d65808cfeca6.png)

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
