### ISSUE TITLE
Spotify icon request

### ISSUE THREAD

**Issue by josephpliu** [WordPress/dashicons#331]
Is it possible to create a Spotify icon based on the Spotify brand mark? 
https://developer.spotify.com/branding-guidelines/

**Comment by field2** [comment]
[spotify.svg.zip](https://github.com/WordPress/dashicons/files/4393986/spotify.svg.zip)
![image](https://user-images.githubusercontent.com/1656980/77765232-5242fc80-7014-11ea-9a44-7723bd97f47f.png)

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
