### ISSUE TITLE
Style of name

### ISSUE THREAD

**Issue by ttodua** [WordPress/dashicons#334]
I think it would be better if the name was in one line, instead of two lines:

![Image](https://i.imgur.com/9lSeEJd.png)

**Comment by mrpritchett** [comment]
Disagree. There are some longer ones and not breaking would mean the name would bleed into the paragraph to the right.  This is especially true on mobile. An argument could be made to reduce the size of the dashicon in context to allow for longer names, but I digress.

**Comment by field2** [comment]
We can close this.
