### ISSUE TITLE
Can we please have a dashicon for calculator?

### ISSUE THREAD

**Issue by sysqo82** [WordPress/dashicons#335]

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77765848-3855e980-7015-11ea-8bd7-a217ef7794e7.png)
[calculator.svg.zip](https://github.com/WordPress/dashicons/files/4394030/calculator.svg.zip)

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
