### ISSUE TITLE
Dashicon additions

### ISSUE THREAD

**Issue by cadillac1960** [WordPress/dashicons#339]
Would like to see calculator and/or dollar sign added to the dashicons for WP if possible.

Thank you for your efforts.

C

**Comment by Zodiac1978** [comment]
The dollar sign is not very generic (and I don't think we can add every currency in the world). There is already a generic money icon which could be of help here:
https://developer.wordpress.org/resource/dashicons/#money

Calculator icon is an interesting idea!

**Comment by field2** [comment]
Calculator icon added to previous issue. We can close this..

**Comment by Zodiac1978** [comment]
https://github.com/WordPress/dashicons/issues/335
https://github.com/WordPress/dashicons/issues/318
