### ISSUE TITLE
Can the Gutenberg icons be added to the docs?

### ISSUE THREAD

**Issue by keefyhub** [WordPress/dashicons#341]
https://developer.wordpress.org/resource/dashicons/

would like to be able to see the icons available in Gutenberg on here for when I am registering new blocks and would like to add a relevant icon.

**Comment by jeffpaul** [comment]
@keefyhub those been merged into the repo ([see closed PRs here](https://github.com/WordPress/dashicons/pulls?q=is%3Apr+gutenberg+is%3Aclosed)), but in order for them to appear on the Dashicons site we need to get https://core.trac.wordpress.org/ticket/41074 committed (which will fingers crossed happen this week in time for WordPress 5.2 beta).
