### ISSUE TITLE
Please new icon super hero

### ISSUE THREAD

**Issue by ravalos7** [WordPress/dashicons#342]
Its possible add new icon of a super hero? Thanks to all!!!

**Comment by Zodiac1978** [comment]
What is the need to have a super hero as an icon in the WordPress admin area?

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77767785-f11d2800-7017-11ea-986e-6bb22dfdfd93.png)
![image](https://user-images.githubusercontent.com/1656980/77767724-dba7fe00-7017-11ea-8f8a-2f0eed52ebb2.png)
[superhero-alt.svg.zip](https://github.com/WordPress/dashicons/files/4394133/superhero-alt.svg.zip)
[superhero.svg.zip](https://github.com/WordPress/dashicons/files/4394134/superhero.svg.zip)

Two options, fun one

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
