### ISSUE TITLE
new dashicons proposal

### ISSUE THREAD

**Issue by arena94** [WordPress/dashicons#345]
Proposing new icons :

businesspeople (3)
hourglass (1)
privacy (3)

[dashicons.zip](https://github.com/WordPress/dashicons/files/2973794/dashicons.zip)

**Comment by arena94** [comment]
was thinking also of a 'at' dashicon

[at.zip](https://github.com/WordPress/dashicons/files/2973823/at.zip)

**Comment by Zodiac1978** [comment]
For Businesspeople these icons could be used:
https://developer.wordpress.org/resource/dashicons/#groups
https://developer.wordpress.org/resource/dashicons/#businesswoman
https://developer.wordpress.org/resource/dashicons/#businessman
https://developer.wordpress.org/resource/dashicons/#businessperson

Hourglass and privacy are interesting ideas.

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77768618-1bbbb080-7019-11ea-895e-7419a1192490.png)
[hourglass.svg.zip](https://github.com/WordPress/dashicons/files/4394196/hourglass.svg.zip)
 hourglass

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77769513-54a85500-701a-11ea-9efa-8138f2d9415c.png)
[privacy.svg.zip](https://github.com/WordPress/dashicons/files/4394235/privacy.svg.zip)
Privacy. We already have a lock, so this might not be necessary

**Comment by arena94** [comment]
@Zodiac1978 

Thank you for the comment.
Just posting the 4 icons you mentioned for display.
Regards

![hourglass svg](https://user-images.githubusercontent.com/1025411/77774358-3575eb80-704b-11ea-89c0-212e621ef7d1.png)
hourglass

![privacy svg](https://user-images.githubusercontent.com/1025411/77774361-360e8200-704b-11ea-80f8-124b4543d20a.png)
privacy

![privacy-alt svg](https://user-images.githubusercontent.com/1025411/77774362-360e8200-704b-11ea-971f-a8e1708ab59b.png)
privacy-alt

![privacy-alt2 svg](https://user-images.githubusercontent.com/1025411/77774363-36a71880-704b-11ea-8f72-8537394b9726.png)
privacy-alt2

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
