### ISSUE TITLE
Dashicon social media

### ISSUE THREAD

**Issue by archenemys** [WordPress/dashicons#359]
I just read that you guys were not developing any new social media icons for the future...

This is a foolish choice.  Despite there being so many other social icon options out there, it is imperative that the at the very least the most "popular" ones be added by you guys.  Facebook, Instagram, Snapchat, Youtube, Twitter are among the most popular, most used and highest ranked globally.  If the basic icons are not available what's the point of Dashicons icon fonts?

Using Font Awesome, as one person suggested, clearly defeats the purpose dashicons.  It is not good developing practice to use font awesome just for one instagram icon font simply because it's not available in wordpress.  That is foolish.

Pretty much everyone has instagram, snapchat ect.  These should clearly be a standard addition to dashicons as it's come a standard for developing!!!

**Comment by field2** [comment]
If someone writes a list up of what we're missing, I'll add them here. We have Facebook, linkedin is coming in the next build. 
-Instagram and youtube should be added. There are tons of other platform, so maybe just the top 4 or 5 or I'll be doing icons forever

**Comment by field2** [comment]
[instagram.svg.zip](https://github.com/WordPress/dashicons/files/4394315/instagram.svg.zip)
![image](https://user-images.githubusercontent.com/1656980/77770613-e95f8280-701b-11ea-8582-0151fc1361fe.png)
Instagram

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77771080-9df9a400-701c-11ea-8910-62d2d04574c0.png)

[youtube.svg.zip](https://github.com/WordPress/dashicons/files/4394345/youtube.svg.zip)
Youtube

**Comment by Zodiac1978** [comment]
Instagram is already there: https://developer.wordpress.org/resource/dashicons/#instagram

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
