### ISSUE TITLE
Google+ Icon can be removed or replaced with just the G

### ISSUE THREAD

**Issue by webdesignacademy** [WordPress/dashicons#363]
As we all now know Google+ is a gonner so the icon can be removed or rather replaced with just the G.

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77772451-89b6a680-701e-11ea-9a65-c6f063427f41.png)
[google.svg.zip](https://github.com/WordPress/dashicons/files/4394408/google.svg.zip)

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
