### ISSUE TITLE
Bank and money icon

### ISSUE THREAD

**Issue by jinuvijay5** [WordPress/dashicons#367]
Hi,
I need a bank and money dashicons for my new project.

**Comment by Zodiac1978** [comment]
There is a money icon in the set:
https://developer.wordpress.org/resource/dashicons/#money

What do you mean with bank icon?

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77772868-2bd68e80-701f-11ea-96fd-ee504303e6f1.png)
[bank.svg.zip](https://github.com/WordPress/dashicons/files/4394438/bank.svg.zip)
Bank icon if you need it

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
