### ISSUE TITLE
pinterest

### ISSUE THREAD

**Issue by theomanel** [WordPress/dashicons#380]
![icopint-04](https://user-images.githubusercontent.com/54857974/64197201-b722e380-ce85-11e9-993c-27a414ac3b27.png)

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77773919-a7850b00-7020-11ea-90ae-2e4fdf815267.png)
[pinterest.svg.zip](https://github.com/WordPress/dashicons/files/4394512/pinterest.svg.zip)

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
