### ISSUE TITLE
Would like an icon for Amazon 

### ISSUE THREAD

**Issue by BillyMartin1964** [WordPress/dashicons#383]
Would like an icon for Amazon to use on the dashboard when doing plugins for Amazon affiliates products, please.

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77774409-66d9c180-7021-11ea-9a7e-cc523571afbd.png)
[amazon.svg.zip](https://github.com/WordPress/dashicons/files/4394546/amazon.svg.zip)

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77774782-fd0de780-7021-11ea-8f82-f3bafe7333d3.png)
[whatsapp.svg.zip](https://github.com/WordPress/dashicons/files/4394583/whatsapp.svg.zip)
Whatsapp

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
