### ISSUE TITLE
Create new dash icons for Whatsapp

### ISSUE THREAD

**Issue by rectopul** [WordPress/dashicons#384]
Insert Whatsapp Icon in Dashicons for socia media links

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77774880-23cc1e00-7022-11ea-988c-547cfd13457f.png)
[whatsapp.svg.zip](https://github.com/WordPress/dashicons/files/4394587/whatsapp.svg.zip)

Whatsapp (also on previous issue)

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
