### ISSUE TITLE
Request for car dashicon

### ISSUE THREAD

**Issue by wwwlabsG** [WordPress/dashicons#385]
![car-icon-20](https://user-images.githubusercontent.com/50685207/67003440-38ed6a00-f0de-11e9-9cf7-9cfb78d4ed68.png)
I'd very much welcome a car dashicon under the 'Misc' category, something like the attached file. Thank you!

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77777650-3d6f6480-7026-11ea-8943-9a201c4cf2c1.png)
[car.svg.zip](https://github.com/WordPress/dashicons/files/4394761/car.svg.zip)

**Comment by wwwlabsG** [comment]
Cool! Thank you! J
