### ISSUE TITLE
Eyes are not the same (f177 & f530)

### ISSUE THREAD

**Issue by JJJ** [WordPress/dashicons#392]
There are two Dashicons that include eyes in them, one open and one with a line through it. These eyes are not the same size, in the same position, or using the same stroke.

Toggling between the two icons makes for an inconsistent appearance.

Below is the New Password UI in WordPress Core. One eye is used for the Password field type, another for the Plaintext field type. Clicking Show/Hide toggles it. A painters eye will identify the difference right away, but I've also overlapped them with 50% opacity so the difference is more obvious:

![eyes](https://user-images.githubusercontent.com/88951/68532233-6c3ba700-02e0-11ea-95d4-feb0b4816003.jpg)

**Comment by field2** [comment]
This needs to be unzipped, and the folder contents added to /sources/svg
Then run grunt and do a PR

Then agree to come to the next WordCamp Buffalo once it's announced

[Archive.zip](https://github.com/WordPress/dashicons/files/3832594/Archive.zip)

**Comment by davewhitley** [comment]
Gridicons has similar icons, and I don't think they have this same issues. The 2 eye icons are the same, except for the diagonal line. Just providing in case it's helpful http://automattic.github.io/gridicons/

![Screen Shot 2019-11-15 at 1 43 15 PM](https://user-images.githubusercontent.com/618551/68970873-e91dc380-07ad-11ea-9f0a-a6c4c2528b5c.png)
![Screen Shot 2019-11-15 at 1 43 11 PM](https://user-images.githubusercontent.com/618551/68970876-eae78700-07ad-11ea-9040-41e2ef114e73.png)

**Comment by JJJ** [comment]
May need to reopen this. I think something is wrong.

These two icons ended up pretty mangled in the font. They look OK in the sprite SVG though.

<img width="1208" alt="Screen Shot 2019-11-15 at 2 19 51 PM" src="https://user-images.githubusercontent.com/88951/68973132-16b93b80-07b3-11ea-9f66-64d05f935b67.png">

**Comment by JJJ** [comment]
I've tried again to recompile these assets, and they still look like above. cc @field2 for a consult?

**Comment by field2** [comment]
Yeah, it looks like the code that Illustrator pushed out was in an incompatible format. I'm remaking the svg files and comparing them to the prior versions.

**Comment by field2** [comment]
[Archive.zip](https://github.com/WordPress/dashicons/files/3869947/Archive.zip)
Can you try again with the attached svgs? I ran a build on my local system with these and it fixed the issue in the font: 
![image](https://user-images.githubusercontent.com/1656980/69252080-754e3300-0b80-11ea-8aeb-85c5848c3993.png)

**Comment by Zodiac1978** [comment]
Is this already fixed and can be closed @field2 ?

**Comment by field2** [comment]
I just installed the dashicons.ttf by downloading it from the master branch, and it looks like it is still messed up. @jasmussen , can you take a look at this? 
![image](https://user-images.githubusercontent.com/1656980/77685230-86b1ac80-6f71-11ea-9c0c-01c99282fb1f.png)

**Comment by field2** [comment]
(Les yeux sans visage)
The Eyes Are Not the Same
-Billy Idol
[sorry couldn't help myself]

**Comment by field2** [comment]
It looks like this issue is affecting many of the new icons I just added. I think it's something wrong with grunt-webfont, see this issue: https://github.com/sapegin/grunt-webfont/issues/390

**Comment by jasmussen** [comment]
I created a fix in #409. 

As you can see from the GIF there, the vectors for the two eye-icons are perfectly placed on top of each other, so if there is mis-alignment, it must be from CSS.

**Comment by JJJ** [comment]
Thanks @jasmussen 🙏
