### ISSUE TITLE
[New Icon Request] Food related icons

### ISSUE THREAD

**Issue by anthonykusuma** [WordPress/dashicons#395]
I know we already have dashicons-carrot, but I want to request another icons that are related to food. For example:

- [utensils](https://fontawesome.com/icons/utensils?style=solid) on Fontawesome
- [drumsticks-bite](https://fontawesome.com/icons/drumstick-bite?style=solid) on Fontawesome

It might be useful for someone who has restaurant websites with Custom Post Type in the menu. Thank you.

**Comment by stiotti** [comment]
+1 for this

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77779744-5b8a9400-7029-11ea-985b-4df96aa5c6b4.png)
[food1.svg.zip](https://github.com/WordPress/dashicons/files/4394873/food1.svg.zip)

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77780533-86291c80-702a-11ea-88c6-7fa41ef5b899.png)
[food2.svg.zip](https://github.com/WordPress/dashicons/files/4394921/food2.svg.zip)
drumstick

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77780721-d1432f80-702a-11ea-9da9-edcc14b53109.png)
[drumstick.svg.zip](https://github.com/WordPress/dashicons/files/4394929/drumstick.svg.zip)
drumstick

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
