### ISSUE TITLE
[New icons request]

### ISSUE THREAD

**Issue by gcluley** [WordPress/dashicons#398]
Would be great to have some Dashicons to represent:

* PDF file
* LinkedIn (hey, Google+ exists as an icon and that's dead :)
* Reddit

Thanks for your consideration

**Comment by Zodiac1978** [comment]
Linkedin already mentioned in #309

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77783940-1584fe80-7030-11ea-8d22-4445ae7d4253.png)
[pdf.svg.zip](https://github.com/WordPress/dashicons/files/4395106/pdf.svg.zip)

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77784905-b88a4800-7031-11ea-81f5-8898bdaea29e.png)
[reddit.svg.zip](https://github.com/WordPress/dashicons/files/4395131/reddit.svg.zip)

reddit

**Comment by jasmussen** [comment]
Closing this as the icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
