### ISSUE TITLE
Fullscreen icon

### ISSUE THREAD

**Issue by abuyoyo** [WordPress/dashicons#403]
Request for `fullscreen` / `fullscreen-close` icons.
Preferably an icon with a consistent lineweight.

The current `editor-expand` icon with the square in the middle and the tapering lineweight are not very clear and not very readable. Especially when small. Its counterpart `editor-contract` with the huge square and negative space arrows is even less readable.

Gridicons have nice clean readable-at-any-size `fullscreen` icons with non-tapering lines. They also work well as counterparts.
Wikipedia's minimalist (only 2 arrows) icon is also worth looking at. Also with a non-tapering stroke which is a must for readability.

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77785391-7f060c80-7032-11ea-90da-49ce1eb6c0b7.png)
![image](https://user-images.githubusercontent.com/1656980/77785904-4286e080-7033-11ea-82a2-4b8e601b09a5.png)
[fullscreen-exit-alt.svg.zip](https://github.com/WordPress/dashicons/files/4395169/fullscreen-exit-alt.svg.zip)
[fullscreen-alt.svg.zip](https://github.com/WordPress/dashicons/files/4395170/fullscreen-alt.svg.zip)

**Comment by jasmussen** [comment]
Closing this as the fullscreen icons are in the font as of #411. The next step is for this icon to land in WordPress 5.5. Thanks!
