### ISSUE TITLE
Xing logo

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/dashicons#406]
Besides LinkedIn a logo for Xing would be great:

https://dev.xing.com/logo_rules
For example: https://www.iconfinder.com/icons/1608742/xing_icon

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/77925435-d8f51500-7272-11ea-8520-95a508158310.png)

[xing.svg.zip](https://github.com/WordPress/dashicons/files/4403520/xing.svg.zip)

**Comment by Zodiac1978** [comment]
Thank you @field2 !
