### ISSUE TITLE
LinkedIn Icon

### ISSUE THREAD

**Issue by zigojacko** [WordPress/dashicons#412]
I can't quite believe there isn't an icon for LinkedIn... 

Unless I'm missing it somehow?

**Comment by zigojacko** [comment]
Even though past issues shows that there was one requested and designed...

https://github.com/WordPress/dashicons/issues/309

🤔

**Comment by jasmussen** [comment]
Hello, yes, the linkedin icon has been created:

<img width="202" alt="Screenshot 2020-04-20 at 12 34 04" src="https://user-images.githubusercontent.com/1204802/79742547-42f95b00-8303-11ea-866e-37906249976c.png">

But it is not yet in WordPress. Hopefully it will land in WordPress 5.5.

In the mean time, you _could_ download it directly from here: https://github.com/WordPress/dashicons/tree/master/icon-font

Hope that helps!
