### ISSUE TITLE
Social Dashicons - add to most imporant and remove G+

### ISSUE THREAD

**Issue by webbeetle** [WordPress/dashicons#414]
Since WP 5.4 has a dedicated block for social icons it seems urgent to add some of the most popular social networks:
1. Pinterest (really urgent, otherwise this new block will be of little use to many bloggers)
2. Youtube
...and maybe:
3. Reddit
4. Flipboard

The icon for Google Plus G+ should be removed. Hasn't it been a year since Google closed it down?

**Comment by jasmussen** [comment]
Hi, thanks for the ticket! The "Social Links" block does not use Dashicons, but uses inline SVG. So you should feel free to report this for the block editor directly in https://github.com/WordPress/gutenberg.

Would also note that the Google Plus logo has been updated to just be the Google G in the Dashicons font.
