### ISSUE TITLE
Goodreads Icon

### ISSUE THREAD

**Issue by luninar** [WordPress/dashicons#415]
Hi! I'm an author/editor and one of my main social media profiles is on Goodreads. Can an icon for that platform be added to dashicons?

**Comment by jasmussen** [comment]
Hello! As of [this post](https://make.wordpress.org/design/2020/04/20/next-steps-for-dashicons/), Dashicons is no longer taking icon requests. For a goodreads icon, and just logos in general, I can recommend the "Social Logos" project: https://github.com/Automattic/social-logos — you should feel free to create an issue for a Goodreads icon there! 

Thanks for your time.
