### ISSUE TITLE
light switch icon

### ISSUE THREAD

**Issue by doug-a-licious** [WordPress/dashicons#416]
Hello, I am looking for an icon, options of switching on and off.  Dark to light and light to dark imagery.

**Comment by jasmussen** [comment]
Hello! As of [this post](https://make.wordpress.org/design/2020/04/20/next-steps-for-dashicons/), Dashicons is no longer taking icon requests. In the mean time, the Material icon set has a switch that might work for you: https://material.io/resources/icons/?search=switch&icon=toggle_off&style=baseline

Hope that helps and thank you!

**Comment by doug-a-licious** [comment]
Thanks Joen.

~Doug
