### ISSUE TITLE
Dashicons issue

### ISSUE THREAD

**Issue by Wsreylet** [WordPress/dashicons#421]
Dashicons issue

_Originally posted by @Wsreylet in https://github.com/WordPress/dashicons/issues/333_

**Comment by desrosj** [comment]
I'm not quite sure what the issue being reported here is. Additionally, the linked issue (#333) appears to be requesting a trademark icon. No more new icons are being considered for the Dashicons font.

For those reasons, I am going to close out. If these interpretations are incorrect, feel free to reopen. But please provide a much more detailed description of what is being reported.
