### ISSUE TITLE
CSS validation issue

### ISSUE THREAD

**Issue by Komagain** [WordPress/dashicons#422]
Hello, I have ran an HTML validator on my website,
It has gathered several errors tied to dashicon:

> Error: CSS: speak: none is not a speak value.

```
.dashicons{
	font-family:dashicons;
	display:inline-block;
	line-height:1;
	font-weight:400;
	font-style:normal;
	**speak:none;**
	text-decoration:inherit;
	text-transform:none;
	text-rendering:auto;
	-webkit-font-smoothing:antialiased;
	-moz-osx-font-smoothing:grayscale;
	width:20px;
	height:20px;
	font-size:20px;
	vertical-align:top;
	text-align:center
	}
```
is there a way to remove the error?

Thanks

**Comment by desrosj** [comment]
Hi @Komagain,

Thanks for reporting this! `none` is indeed an invalid value for `speak`. I've opened up a PR for this, and we'll get this corrected in an upcoming version of WordPress.
