### ISSUE TITLE
Add github icon

### ISSUE THREAD

**Issue by rifqirosyidi** [WordPress/dashicons#425]
I try using GitHub icon by using "dashicon dashicon-github". but the icons seems unavailable.

**Comment by amro-k-saleh** [comment]
hello, @rifqirosyidi I hope you are doing well.

unfortunately, according to my knowledge, the Dashicons project - in short - are stopping to accept new requests for logos
please check https://make.wordpress.org/design/2020/04/20/next-steps-for-dashicons/
for the reasons stated in the article mentioned in the article above.

a simple solution could be using Fontawesome (https://fontawesome.com/).

but you can always make your own web font easily:
1. download or design the icons and turn them into SVG with free software like Inkscape.
2. then use websites like IcoMoon (https://icomoon.io/) to turn them into a web font.

I really hope you found that helpful.

**Comment by amro-k-saleh** [comment]
If you just need the GitHub logo you can download it from https://github.com/logos and use it as an SVG directly.
