### ISSUE TITLE
The center-top button in the calculator icon isn't circular

### ISSUE THREAD

**Issue by zackkatz** [WordPress/dashicons#426]
<img width="856" alt="Two circles, one oblong shape in the middle" src="https://user-images.githubusercontent.com/870979/105883057-652bb200-5fd4-11eb-985e-efe19d57815f.png">

I understand Dashicons is frozen, but surely fixing this warrants consideration! :-)

**Comment by desrosj** [comment]
Closing [per this comment](https://github.com/WordPress/dashicons/pull/427#issuecomment-1405191927).
