### ISSUE TITLE
Move / Drag

### ISSUE THREAD

**Issue by melchoyce** [WordPress/dashicons#43]

**Comment by melchoyce** [comment]
Two options:

![dashicons-move](https://cloud.githubusercontent.com/assets/2846578/10382745/2b7847e8-6df5-11e5-8d1c-7d3ebb5ccfbd.png)
![dashicons-move-alt](https://cloud.githubusercontent.com/assets/2846578/10382744/2b6fd19e-6df5-11e5-9866-02f5db5a503b.png)

**Comment by donnamcmaster** [comment]
I like the 2nd (alt) one

**Comment by field2** [comment]
#2 (the simpler one)

**Comment by joseluis** [comment]
Between those two, the second one without a doubt

**Comment by melchoyce** [comment]
Move icon in .ai format: https://cloudup.com/cJZ74VUIKWX

**Comment by helgatheviking** [comment]
:100:
