### ISSUE TITLE
Upgrade Site Health “Great job!” Checkmark (Dashicon)

### ISSUE THREAD

**Issue by Jetxpert** [WordPress/dashicons#432]
**Reference:** [WordPress Core Ticket No. 53980 | Comment No. 2](https://core.trac.wordpress.org/ticket/53980#comment:2)

**Request:**

Following the guidance provided in reference comment, this is to request WordPress upgrade the current dashicon used for the Site Health "Great job!" screen 

**from this:**

"dashicons-yes"  (f147) 
<img src="https://i.ibb.co/4PQst8s/dashicon-yes-f147.png" alt="dashicon-yes-f147" border="0">

**to this:**

"dashicons-yes-alt" (f12a)

<img src="https://i.ibb.co/fCkL2jC/dashicon-yes-alt-f12a.png" alt="dashicon-yes-alt-f12a" border="0">

**Reason for Request:**

Upgrade (i.e., modernize) the looks of affected WordPress screen.

**Note:**

It would be great to use a better-looking dashicon or image. However, current [WordPress design limitations](https://developer.wordpress.org/resource/dashicons/#editor-ul) are forcing us to recommend the above.

Thank you!

**Comment by Jetxpert** [comment]
**Useful:**

Until the above change is made, the following will accomplish the intent of our request:

Go to file: `/wp-admin/site-health.php` and change Line 203

From:

<span class="dashicons dashicons-yes"></span>

To: 

<span style="margin-bottom:20px;" class="dashicons dashicons-yes-alt"></span>

Cheers!

**Comment by desrosj** [comment]
Directing this request here was a misunderstanding! I've reopened the Trac ticket and added more details.
