### ISSUE TITLE
Printer

### ISSUE THREAD

**Issue by melchoyce** [WordPress/dashicons#49]
From: https://core.trac.wordpress.org/ticket/32614

**Comment by nathanduckett** [comment]
Hi Melchoyce,

I originally requested this on wordpress core trac, Are all dashicons now requested/suggested on git hub going forward?

Also if I have a go at designing this icon myself what format does it need to be in? Are there any guidelines to follow?

Thanks,
ND

**Comment by melchoyce** [comment]
Yup, we're going to be moving all requests to Github so they're easier to find & review.

Great to hear you want to have a go at designing the icon! We have a work-in-progress style guide for designing Dashicons that can get you started: https://make.wordpress.org/design/dashicons-style-guide/ We'll need the icon in some kind of vector format (.ai, .eps, .svg, etc.).

Let me know if you have any questions :)

**Comment by field2** [comment]
@nathanduckett any progress on the printer icon?

**Comment by nathanduckett** [comment]
Hello,

I finally had chance to have a go at making a printer dashicon, I basically started with the media-text dashicon and drew around that, I have attached 5 I have been playing around with. 

Feedback/tips much appreciated :)

Nathan Duckett

[dashicons.zip](https://github.com/WordPress/dashicons/files/108057/dashicons.zip)

**Comment by nathanduckett** [comment]
Hi Melchoyce,

Just nudging to see if you have had chance to see my printer dashicon.

**Comment by field2** [comment]
I think printer-1 is closest. Can you do an option with no lines on the paper, no buttons/lights on the printer, and part of the paper coming out of the bottom?

**Comment by nathanduckett** [comment]
@field2 

Ok so I have added 4 variations to printer-1. I'm thinking the no-buttons-line goes well.

[dashicons-printer.zip](https://github.com/WordPress/dashicons/files/181262/dashicons-printer.zip)

**Comment by nathanduckett** [comment]
@melchoyce @field2 

Bump! any update?

Thanks
Nathan

**Comment by nathanduckett** [comment]
@melchoyce @field2 

Has my messages been missed I wonder? See attached design.

Ok so I have added 4 variations to printer-1. I'm thinking the no-buttons-line goes well.

[dashicons-printer.zip](https://github.com/WordPress/dashicons/files/671740/dashicons-printer.zip)


Thanks
Nathan

**Comment by field2** [comment]
Hi Nathan,
These look great. We're still figuring out how to handle the new icon designs and requests. Once we have a new system for handling icons set, I'll give you feedback and we'll work one of these in.  Stay tuned!
