### ISSUE TITLE
Should we show Buddy/bbPress icons on the Developer Resource page?

### ISSUE THREAD

**Issue by melchoyce** [WordPress/dashicons#56]
Here: https://developer.wordpress.org/resource/dashicons

**Comment by ntwb** [comment]
@melchoyce I've mentioned this in both bbPress and BuddyPress Slack channels asking for feedback :)

**Comment by ntwb** [comment]
My opinion is I'm not opposed to it, for bbPress I have the documented on our codex page so it's not like this information is not already available for bbPress :smirk: 

https://codex.bbpress.org/official-logos-and-icons/

**Comment by melchoyce** [comment]
> I've mentioned this in both bbPress and BuddyPress Slack channels asking for feedback :)

Thanks :+1:

**Comment by robkk** [comment]
I say sure, why not. Anything in the icon set should be visible on that page in my opinion.

**Comment by johnjamesjacoby** [comment]
Yes, please! I forget why they were omitted, but I suspect there was a good reason.

WordPress core also does not currently declare any CSS classes for BuddyPress & bbPress dashicons, and the bb's do not registered their own either.

I'm not the type to ask for preferential treatment, but it would be excellent if WordPress core named & declared the bb's icons for the world. (The classes listed on bbPress's Logos & Icons page don't seem to exist as far as I can tell.)

**Comment by melchoyce** [comment]
I think the original reason was to keep the icons "pure" so they were only used by the BBs, but I'm totally happy for us to include them in the demo.

**Comment by johnjamesjacoby** [comment]
That sound right. Thanks for this. Is there anything I can do to be helpful?

**Comment by ntwb** [comment]
> The classes listed on bbPress's Logos & Icons page don't seem to exist as far as I can tell.
No idea, I must've created them out of thin air in the original expectation they would be published and public :smirk:

**Comment by TheTracyL** [comment]
This is now has a Meta trac ticket: https://meta.trac.wordpress.org/ticket/2878

**Comment by Zodiac1978** [comment]
The meta ticket is fixed, the BuddyPress/bbPress icons are shown on the page, therefore I close this issue.
