### ISSUE TITLE
Update Google+

### ISSUE THREAD

**Issue by ocean90** [WordPress/dashicons#60]
Current: https://developer.wordpress.org/resource/dashicons/#googleplus

New: https://plus.google.com/+googleplus/posts?pid=6189586698986343618&oid=101560853443212199687

**Comment by melchoyce** [comment]
@field2 Did this end up making into a release? I don't remember

**Comment by ocean90** [comment]
@melchoyce Yup, see https://core.trac.wordpress.org/changeset/37036.

**Comment by melchoyce** [comment]
Cool, closing.

**Comment by field2** [comment]
It did, I think:
https://developer.wordpress.org/resource/dashicons/#googleplus


On Wed, Jul 13, 2016 at 11:14 AM, Mel Choyce <notifications@github.com>
wrote:

> Closed #60 <https://github.com/WordPress/dashicons/issues/60>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/WordPress/dashicons/issues/60#event-721710709>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABlIlMF1qahk_Ofp80uGy0vMCnCG5Zgiks5qVQDFgaJpZM4GLkX5>
> .
>



-- 
Ben Dunkle
716-289-6814
ben@field2.com
field2.com
@empireoflight (WordPress, Twitter, Dribbble)
