### ISSUE TITLE
Mobile icon

### ISSUE THREAD

**Issue by BishoyA** [WordPress/dashicons#67]
Hello,

Could you guys please create an icon for cellular or mobile?

Thanks in advance!

**Comment by melchoyce** [comment]
Hey! We have a mobile/smartphone icon here: https://developer.wordpress.org/resource/dashicons/#smartphone

**Comment by BishoyA** [comment]
Great, thanks :)

As I searched for 'Mobile' and 'Cell' but didn't find anything, so I posted here.
