### ISSUE TITLE
Missing some Icons

### ISSUE THREAD

**Issue by bordoni** [WordPress/dashicons#8]
Hi Guys,

I'm a Plugin developer and I was looking for a Email icon since we have a Share and Share2 icons, I thought that might be a good idea.

There is any ideas to expand this icon base to cover some possibilities like around WordPress and general stuff? 

This would prevent people from including their own fonts/svg files.

**Comment by mikepardeep** [comment]
Hi Guys,
I am Plugin Developer, I am looking for github dash-icon to include in my project. I could not find the icon the wordpress developer dash icons website. Please take my kind request in your consideration. Thank You.
