### ISSUE TITLE
Laptop Icon

### ISSUE THREAD

**Issue by skyshab** [WordPress/dashicons#86]
There are device icons for mobile, tablet and desktop. I could use a laptop icon for my project, and I suspect others may find it useful too.

I created an icon following the Dashicons style guide. 

Hope we can use this.
[laptop.svg.zip](https://github.com/WordPress/dashicons/files/74289/laptop.svg.zip)

**Comment by field2** [comment]
Nice job! Works well with the other device icons. I resized it to fit in a 20x20 grid, otherwise it was good to go.

**Comment by melchoyce** [comment]
@skyshab What's your WordPress.org username? We'll need it to give you core props.

**Comment by skyshab** [comment]
aargh-a-knot

Thanks! glad it was useful.

**Comment by skyshab** [comment]
or skyshab is fine too. I somehow have 2 accounts.
