### ISSUE TITLE
Dashicon for podcast

### ISSUE THREAD

**Issue by rickster04** [WordPress/dashicons#90]
Hi, if you could do a dash icon for podcast that would be great. Fwiw I was thinking along the lines of a stylised pair of headphones..??

all the best

Rick

**Comment by Archie22is** [comment]
+1

**Comment by bahiirwa** [comment]
Check Issue #85

**Comment by Archie22is** [comment]
And a quick google search revealed this: https://wpbeaches.com/hooking-fontawesome-use-wordpress-dashboard-admin-menus/

**Comment by TheTracyL** [comment]
We are very sorry, but we are not adding new icons unrelated to core functionality at this time.

Thank you,
-Tracy
