### ISSUE TITLE
Could we please have a Print/Printer icon?

### ISSUE THREAD

**Issue by phatmano** [WordPress/dashicons#91]
Thank you so much for dashicons for WordPress. Could someone be kind enough to create a  Print/Printer icon? Yes, that very humble icon. We still need those basic icons. Cheers and thanks in advance.

**Comment by TheTracyL** [comment]
We are very sorry your request is so sweet, but we are not adding new icons unrelated to core functionality at this time.

Thank you,
-Tracy
