### ISSUE TITLE
Please add Icons related to recipes, hotels and restaurants

### ISSUE THREAD

**Issue by hassanrazmy** [WordPress/dashicons#94]
Hi,

There are no icons available that can represent food, recipes and restaurants area. (fork, fish, chicken, spoon, plate, bowl, chilly, chef cap etc.)

Thanks & Regards.

**Comment by TheTracyL** [comment]
We are very sorry, but we are not adding new icons unrelated to core functionality at this time.

Thank you,
-Tracy

**Comment by hassanrazmy** [comment]
:( ok

**Comment by bgtbbox** [comment]
I agree !
It's really a shame not to have created, for all this time, icons related to catering, recipes, and hotels!
