### ISSUE TITLE
Add more variations of the earth icon "admin-site"

### ISSUE THREAD

**Issue by iseulde** [WordPress/dashicons#95]
Because we don't all live in America.

**Comment by iseulde** [comment]
Could be based on unicode's earth emoji: 🌎🌍🌏.

**Comment by iseulde** [comment]
Here's a reference from unicode: http://unicode.org/charts/PDF/U1F300.pdf.

**Comment by iseulde** [comment]
http://www.unicode.org/emoji/charts/full-emoji-list.html#1f30d has base64 encoded images.

**Comment by TheTracyL** [comment]
Hello Ella,

Sorry it has taken us so long to get to this! This is a very good idea and I will run it by the team.

Thank you.
-Tracy

**Comment by TheTracyL** [comment]
This is now added to Trac ticket: https://core.trac.wordpress.org/ticket/41074

**Comment by field2** [comment]
How's this?
![new_globes](https://user-images.githubusercontent.com/1656980/27253853-d082fa1c-537c-11e7-8aa3-74fbca49b6e1.png)
I think we should have 3 new globes - 2 additional views and 1 generic view. Or we should just have 1 generic view.
