### ISSUE TITLE
Icon request: twitch

### ISSUE THREAD

**Issue by mtoensing** [WordPress/dashicons#98]
twitch is quite popular. What about adding the twitch icon to dashicons? I mean the smiley chat bubble: http://www.twitch.tv/p/brandassets (at the bottom).
![glitchicon_purpleonwhite](https://cloud.githubusercontent.com/assets/136737/12931055/2100255e-cf7c-11e5-823b-5ea3fb59f09e.png)

If the twitch icon is too specific: what about a generic icon for streaming content besides the video icon?

**Comment by melchoyce** [comment]
Hi there, have you considered using http://fontawesome.io/icons/? We're not currently planning on adding more social icons to Dashicons.

How would you differentiate streaming vs. video?

**Comment by miko007** [comment]
suggesting another font is not quite helpful. on can not force the user to load serveral fonts, just for icons sake.

because dashicons is integrated in wordpress, it would be very convienient to have all popular social icons on hand, and twitch is definately a major one.

**Comment by TheTracyL** [comment]
We are very sorry, but we are not adding new icons unrelated to core functionality at this time.

Thank you,
-Tracy
